### ISSUE TITLE
Can't add variation item to order's line items on the backend.

### ISSUE THREAD

**Issue by six006** [VirtoCommerce/vc-community#100]
I want to add a variation item to cusomter order,but I can't see any  "add selected" button on the variation item list.

![3](https://cloud.githubusercontent.com/assets/5348170/10509275/74a4e6a6-735e-11e5-8238-aafdd9b4fbb4.jpg)

**Comment by tatarincev** [comment]
Thanks a lot for the help!
We missed  the addition of variations in the order, be sure to fix that in current milestone.
