### ISSUE TITLE
Commerce Manager Login-View doesn´t appear in Chrome and IE

### ISSUE THREAD

**Issue by Rushmore74** [VirtoCommerce/vc-community#102]
Either in Chrome nor in IE the Login-View appears.

In Fiddler I see HttpStatus 500 with the following exception:

HTTP/1.1 500 Internal Server Error
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; charset=utf-8
Expires: -1
Server: Microsoft-IIS/8.5
X-AspNet-Version: 4.0.30319
Persistent-Auth: true
X-Powered-By: ASP.NET
Date: Fri, 16 Oct 2015 07:14:32 GMT
Content-Length: 1574

{
  "message": "An error has occurred.",
  "exceptionMessage": "Object reference not set to an instance of an object.",
  "exceptionType": "System.NullReferenceException",
  "stackTrace": "   at VirtoCommerce.Platform.Data.Security.SecurityService.UserHasAnyPermission(String userName, String[] scopes, String[] permissionIds)\r\n   at VirtoCommerce.Platform.Core.Security.CheckPermissionAttribute.IsAuthorized(ISecurityService securityService, IPrincipal principal)\r\n   at VirtoCommerce.Platform.Core.Security.CheckPermissionAttribute.IsAuthorized(HttpActionContext actionContext)\r\n   at System.Web.Http.AuthorizeAttribute.OnAuthorization(HttpActionContext actionContext)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
}

In Mozilla the Login-Dialog appears. After pressing Escape I see the Commerce Manager Login-View and can login as expected.

Any suggestions?

Regards
Carlo

**Comment by Rushmore74** [comment]
Solved it.

Anonymous Authentication and Windows Authentication is Enabled per default.
Disabling Windows Authentication did the job.

**Comment by tatarincev** [comment]
Anyway exception not should apper, we will fix this bug. Thanks.

**Comment by Rushmore74** [comment]
Yes of course. Just to let you know. Software stability and quality is a good thing.
The exception doesn´t appear in the browser, The browser was empty. Then I tried again with fiddler in the background and saw the exception in the response. But anyway in the perspective of a "normal" user it should not happen.
