### ISSUE TITLE
I can't find any place to use the Price list assignments

### ISSUE THREAD

**Issue by six006** [VirtoCommerce/vc-community#103]
How to use the Price list assignments?
I can't find the description on http://docs.virtocommerce.com/display/vc2userguide/9.+Price+Lists
I want to use it !
![1](https://cloud.githubusercontent.com/assets/5348170/10557070/7ad10368-74ce-11e5-9ae9-430989e719b6.jpg)

**Comment by Woland2k** [comment]
Price lists are automatically assigned to a customer when he first logins to the store, based on the store catalog. The conditions are then evaluated in the price list assignments priority and first price found is displayed to a customer.

**Comment by six006** [comment]
Thank you!
