### ISSUE TITLE
Can not add the item to the cart on the sample clothing store!

### ISSUE THREAD

**Issue by six006** [VirtoCommerce/vc-community#105]
When I open the url "http://demo.virtocommerce.com/clothing/v-dresses/white-strappy-embroidered-sun-dress",then click the button "BUY NOW" it return javascript error :Uncaught TypeError: Shopify.getCart is not a function!

![1](https://cloud.githubusercontent.com/assets/5348170/10572572/4028a70c-767c-11e5-90e8-38a125b020c6.jpg)

**Comment by Woland2k** [comment]
We found an issue, the api.jquery.js file was not included as part of the website project, only as part of repository and thus was not deployed. It should be fixed now.
