### ISSUE TITLE
Suggest,move the third javascript libs into the project

### ISSUE THREAD

**Issue by six006** [VirtoCommerce/vc-community#107]
When I open the url http://demo.virtocommerce.com/admin,
I find that some third javascript libs can't be loaded,for example 
 <script src="https://apis.google.com/js/platform.js" async defer></script>

![1](https://cloud.githubusercontent.com/assets/5348170/10599285/32fb57a2-7733-11e5-9291-0d31afd1a1d6.png)

I suggest that it is best to move the third javascript libs into the project !

**Comment by six006** [comment]
Or use a  setting file to config local or cdn  js lib

**Comment by tatarincev** [comment]
Thanks for sugestion, in our project we use *bower*  for manage thrid js packges and all of them loads from our side. You have lucky to find only one of two js not included localy :)
Anyway thanks for sugestion!

**Comment by six006** [comment]
Can I remove the scripts on the document
<script src="https://apis.google.com/js/platform.js" async defer></script>

**Comment by six006** [comment]
Can I remove the scripts url https://apis.google.com/js/platform.js on the document

**Comment by eMazeika** [comment]
Thanks again for being such persistent. I've just removed this script.
