### ISSUE TITLE
Setting Language doesn't work for Store

### ISSUE THREAD

**Issue by serkanz** [VirtoCommerce/vc-community#108]
When we set the language of a store other than English (let's say de-DE) store continues to show English language.

**Comment by tatarincev** [comment]
You have a deutschland products descriptions or cms items?

**Comment by serkanz** [comment]
Hello,

No , we have used 2.5 release and installed clothing demo on it . Our server uses Turkish regional settings so we had to set IIS globalization settings to English.

**Comment by tatarincev** [comment]
IIS localization setting does not should relate to store content localization.
Unfortenately demo data not contains multilingual resources only english but we definetly will add it in future release.

**Comment by tatarincev** [comment]
And more we find some issues on our frontend realization related to localization and need time to fix it

**Comment by serkanz** [comment]
Could you provide us a walkthrough about creating a multilangual theme ? or any document about localization?

**Comment by tatarincev** [comment]
Sure, because we use Shopify themes you may read this article https://docs.shopify.com/themes/theme-development/translations/locale-files it 100% compatible with our themes. Currently localization not working because we have some bug and now we just working to fix it.

**Comment by serkanz** [comment]
Thanks for quick replies, could you provide a release (2.3, 2.2 etc) that we can use to test localization works as expected ?

**Comment by tatarincev** [comment]
Not sure, i think we should fix that issue today or tomorrow and you can get dev version for you tests
