### ISSUE TITLE
Uploading a new Asset or Locale File to a Store's Theme Fails

### ISSUE THREAD

**Issue by serkanz** [VirtoCommerce/vc-community#113]
When we try to edit a store's theme by clicking edit css/html button and upload a locale, asset or config file to it from user interface, browser gives an error "Failed to load resource: the server responded with a status of 404 (Not Found)" for resource http://<url>/api/platform/assets/file. 

We can't upload related file to the server. We are using 2.5 version of virtocommerce

**Comment by EugeneOkhriemnko** [comment]
Must work now

**Comment by EugeneOkhriemnko** [comment]
Did you use virtocommerce from dev or master branch?

**Comment by serkanz** [comment]
We used dev branch

**Comment by EugeneOkhriemnko** [comment]
Fix has been commited, try now
