### ISSUE TITLE
"Uploader" must be an instance of FileUploader

### ISSUE THREAD

**Issue by Keutin** [VirtoCommerce/vc-community#114]
Hi, I'm trying to create a new module that uses FileUploader. I receive the following error : "Uploader" must be an instance of FileUploader. I'm quite new to Angular and can't figure out what I need to do in order to inject the FileUploader. I've seen that my error message is declared in AllPackages.js. 
Can you please help me on this?

**Comment by tatarincev** [comment]
Can you send  main module js file of your module?

**Comment by Keutin** [comment]
Thank you for your quick reply. Here's my module content : 

//Call this to register our module to main application
var moduleTemplateName = "platformWebApp.moduleEntity";

if (AppDependencies != undefined) {
    AppDependencies.push(moduleTemplateName);
}

angular.module(moduleTemplateName, [
    'platformWebApp.moduleEntity.blades.bladeEntity'
])
.config(
  ['$stateProvider', '$urlRouterProvider',
    function ($stateProvider, $urlRouterProvider) {
        $stateProvider
            .state('workspace.moduleEntityTemplate', {
                url: '/moduleEntityTemplate',
                templateUrl: 'Scripts/common/templates/home.tpl.html',
                controller: [
                    '$scope', 'platformWebApp.bladeNavigationService', function ($scope, bladeNavigationService) {
                        var blade = {
                            id: 'bladeEntity',
                            controller: 'bladeEntityController',
                            template: 'Modules/$(Nxo.ModuleEntity)/Scripts/blades/bladeEntity.tpl.html',
                            isClosingDisabled: false
                        };
                        bladeNavigationService.showBlade(blade);
                    }
                ]
            });
    }
  ]
)
.run(
  ['$rootScope', 'platformWebApp.mainMenuService', 'platformWebApp.widgetService', '$state', function ($rootScope, mainMenuService, widgetService, $state) {
      //Register module in main menu
      var menuItem = {
          path: 'browse/moduleEntity',
          icon: 'fa fa-cube',
          title: 'ModuleEntity',
          priority: 100,
          action: function () { $state.go('workspace.moduleEntityTemplate') },
          permission: 'moduleEntityPermission'
      };
      mainMenuService.addMenuItem(menuItem);
  }]);

**Comment by tatarincev** [comment]
I think you missed declare **FileUploader** dependency in your controller. 
```javascript
.controller('controllerName', ['FileUploader', function (FileUploader) {
.....
}]);

```
You can see example how to work with fileUploader in this file:
*PLATFORM\Modules\Catalog\VirtoCommerce.CatalogModule.Web\Scripts\blades\images.js*

**Comment by Keutin** [comment]
I think this is what I've done in the controller of my importBlade.
I took as example this file : 
PLATFORM\Modules\Catalog\VirtoCommerce.CatalogModule.Web\Scripts\blades\import\wizard\catalog-CSV-import-wizard.js
Here's my controller code : 

angular.module('platformWebApp.moduleEntity')
    .controller('entityCSVimportWizardController', ['$scope', '$localStorage', 'platformWebApp.bladeNavigationService', **'FileUploader'**, '$log', function ($scope, $localStorage, bladeNavigationService, **FileUploader**, $log) {
        $scope.$log = $log;
        $scope.message = 'Hello World from entityCSVimportWizardController!';
        var blade = $scope.blade;
        blade.isLoading = false;
        blade.title = 'Import catalog from csv';
        blade.subtitle = 'All products will be added to "' + blade.catalog.name + '" catalog';

        $scope.columnDelimiters = [
            { name: "Space", value: " " },
            { name: "Comma", value: "," },
            { name: "Semicolon", value: ";" },
            { name: "Tab", value: "\t" }
        ];


        if (!$scope.uploader) {
            // Creates a uploader
            var uploader = $scope.uploader = new FileUploader({
                scope: $scope,
                headers: { Accept: 'application/json' },
                url: 'api/platform/assets/tmp',
                method: 'POST',
                autoUpload: true,
                removeAfterUpload: true
            });

            // ADDING FILTERS
            // Images only
            uploader.filters.push({
                name: 'csvFilter',
                fn: function (i /*{File|FileLikeObject}*/, options) {
                    var type = '|' + i.type.slice(i.type.lastIndexOf('/') + 1) + '|';
                    return '|csv|vnd.ms-excel|'.indexOf(type) !== -1;
                }
            });

            uploader.onBeforeUploadItem = function (fileItem) {
                blade.isLoading = true;
            };

            uploader.onSuccessItem = function (fileItem, asset, status, headers) {
                $scope.blade.csvFileUrl = asset[0].relativeUrl;

                ////////importResource.getMappingConfiguration({ fileUrl: $scope.blade.csvFileUrl, delimiter: blade.columnDelimiter }, function (data) {
                ////////    if ($localStorage.lastKnownImportData && $localStorage.lastKnownImportData.eTag === data.eTag) {
                ////////        angular.extend(data, $localStorage.lastKnownImportData);
                ////////    }

                ////////    blade.importConfiguration = data;
                ////////    blade.isLoading = false;
                ////////}, function (error) {
                ////////    bladeNavigationService.setError('Error ' + error.status, $scope.blade);
                ////////});
            };
        };

        $scope.canMapColumns = function () {
            return blade.importConfiguration && $scope.formScope && $scope.formScope.$valid;
        }

        $scope.openMappingStep = function () {
            var newBlade = {
                id: "importMapping",
                importConfiguration: $scope.blade.importConfiguration,
                title: 'Column mapping',
                subtitle: 'Manual map product properties to csv columns',
                controller: 'virtoCommerce.catalogModule.catalogCSVimportWizardMappingStepController',
                template: 'Modules/$(VirtoCommerce.Catalog)/Scripts/blades/import/wizard/catalog-CSV-import-wizard-mapping-step.tpl.html'
            };

            blade.canImport = true;
            bladeNavigationService.showBlade(newBlade, $scope.blade);
        };

        $scope.startImport = function () {
            $localStorage.lastKnownImportData = {
                eTag: blade.importConfiguration.eTag,
                propertyMaps: blade.importConfiguration.propertyMaps,
                propertyCsvColumns: blade.importConfiguration.propertyCsvColumns
            };

            var exportInfo = { configuration: blade.importConfiguration, fileUrl: $scope.blade.csvFileUrl, catalogId: blade.catalog.id };
            ////////importResource.run(exportInfo, function (notification) {
            ////////    var newBlade = {
            ////////        id: "importProgress",
            ////////        catalog: blade.catalog,
            ////////        notification: notification,
            ////////        importConfiguration: blade.importConfiguration,
            ////////        controller: 'virtoCommerce.catalogModule.catalogCSVimportController',
            ////////        template: 'Modules/$(VirtoCommerce.Catalog)/Scripts/blades/import/catalog-CSV-import.tpl.html'
            ////////    };

            ////////    $scope.$on("new-notification-event", function (event, notification) {
            ////////        if (notification && notification.id == newBlade.notification.id) {
            ////////            blade.canImport = notification.finished != null;
            ////////        }
            ////////    });

            ////////    blade.canImport = false;
            ////////    bladeNavigationService.showBlade(newBlade, $scope.blade);

            ////////}, function (error) {
            ////////    bladeNavigationService.setError('Error ' + error.status, $scope.blade);
            ////////});
        };

        $scope.setForm = function (form) {
            $scope.formScope = form;
        }

        $scope.blade.onClose = function (closeCallback) {

            if ($scope.blade.childrenBlades.length > 0) {
                var callback = function () {
                    if ($scope.blade.childrenBlades.length == 0) {
                        closeCallback();
                    };
                };
                angular.forEach($scope.blade.childrenBlades, function (child) {
                    bladeNavigationService.closeBlade(child, callback);
                });
            }
            else {
                closeCallback();
            }
        };
    }]);

**Comment by tatarincev** [comment]
In which line you get error?

**Comment by Keutin** [comment]
AllPackages.js line 16

**Comment by tatarincev** [comment]
I got it. Which version of code you use? Empty platform or with modules (manager)?  Can you wait to tomorrow (10:00 UTC)  we try to reproduce and figure out with you problem?

**Comment by Keutin** [comment]
Yes, of course I can wait. Good to know you're on the way...
I use the manager.sln with modules.

**Comment by Keutin** [comment]
Sorry I forgot to mention I'm on version 2.5

**Comment by eMazeika** [comment]
Check your template if the uploader attribute was defined on input element. Like
`<input type="file" multiple uploader="uploader" nv-file-select style="z-index: 0;" tabindex="-1">`

**Comment by Keutin** [comment]
Yes. Here is the template I'm using (inspired from catalog-CSV-import-wizard.tpl.html in catalog module) : 
```html
<div class="blade-content">
	<div class="blade-inner">
		<div class="inner-block">
            <fieldset >
                <div class="form-group">
                    <label class="form-label">Upload Csv file</label>
                    <div class="form-input">
                        <input type="file" uploader="uploader" nv-file-select style="z-index: 0;" tabindex="-1">
                        <input type="text" readonly="" ng-model="blade.csvFileUrl">
                        <button class="btn __file" type="button" onclick="$('input[type=file]').trigger('click')">
                            <i class="btn-ico fa fa-image"></i>
                        </button>
                    </div>
                </div>
                <div ng-show="uploader.isUploading">
                    <div class="sub-t">Upload progress</div>
                    <div class="progress-bar __aqua" ng-style="{'width': uploader.progress + '%'}" style="width: 0%;"></div>
                </div>
            </fieldset>
		</div>
	</div>
</div> 
```

**Comment by eMazeika** [comment]
both the template and controller seems to be correct. Can you clear cache / try another browser to check if browser receives the same code as expected?

**Comment by Keutin** [comment]
Same thing with different browser. Same thing after clearing cache.

**Comment by eMazeika** [comment]
Can you zip and email your project to em@virtoway.com as we don't see any other option to reproduce the issue.

**Comment by Keutin** [comment]
I've just sent you my module. Hope this helps. Thank you.

**Comment by eMazeika** [comment]
I've found out that blade initialization was causing the issue and the js code was never ran. The controller value was incorrect and 'entityCSVimportWizardController' had to be supplied in this case:

//catalog: blade.catalog,
subtitle: 'Choose data format & start import',
controller: 'entityCSVimportWizardController',

also, the catalog value should be set as it's used in the controller later.

Happy developing with VirtoCommerce!

**Comment by Keutin** [comment]
Thank you very much for your time,reactivity and encouragements!
You guys have done an amazing job with Virto Commercet !! 
I guess we'll get back in contact soon ;-)
