### ISSUE TITLE
Platform Export&Import error not display if occur when file  upload

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-community#118]

**Comment by eMazeika** [comment]
Under what circumstances does it occur? How to reproduce?

**Comment by tatarincev** [comment]
Try to change storage path to unexist

**Comment by eMazeika** [comment]
Is it assets issue in general? What provider are you using? AzureBlobStorage?

**Comment by tatarincev** [comment]
local storage

**Comment by eMazeika** [comment]
Still can't reproduce. Are you using an absolute path?  What's your AssetsConnectionString?

**Comment by tatarincev** [comment]
Need generate server error when you upload import file. you can raise manual exception in AssetController or change AssetsConnectionString to notexist storage path
