### ISSUE TITLE
Primary key data type [nvarchar](128)/nvarchar(64)

### ISSUE THREAD

**Issue by mokchhya** [VirtoCommerce/vc-community#123]
I have just started to look into this project virto-commerce. All the tables that i have seen so far have Id as a  primary key with clustered index on it and its data type is either nvarchar(128) or nvarchar(64) . And further more, looking at the entries in the db, random guid is assigned to it as char. 
Currently the size of each Id is : 32 * 2 =64 bytes (32 chars of guid and 2 bytes for each nchar)
    Could not the data type of the primary key be UniqueIdentifier itself? It could have saved  64-16=48 bytes for each row created in data page alone. Not to mention Clustered index will be small. And if there were non clustered index in the table, space will also be saved there since every clustered key will be a part of each non clustered index.

**Comment by tatarincev** [comment]
Hi, thanks for valuable suggestion. It was a mistake in the DB design phase to use nvarchar as primary type. As a consequence this can be of problems with index  fragmentation may cause with performance problems on huge data records. We have plans to change our tables PK to UniqueIdentifier type.
Thanks again for you suggestion.

**Comment by anwaramoon** [comment]
Hi @tatarincev,

Guids are really pain in the neck when it comes to indexing in the database. I bet everyone has their own opinion. As per [this](http://blogs.msdn.com/b/sqlserverfaq/archive/2010/05/27/guid-vs-int-debate.aspx) article int gives you least fragmentation. But obviously this may not be ideal for each project or environment. Especially in replication.

So is it be possible to have an option to either use int, bigint or guid as primary key? 

For instance, what if we leave type of Entity.Id property as string but internally we use a field of specified type to get/set value. This way we do not need make changes in whole framework. We can also expose IIdGenerator interface as well. So id can be generator differently when type is different like [NHibernate](https://github.com/nhibernate/nhibernate-core/blob/5e71e83ac45439239b9028e6e87d1a8466aba551/src/NHibernate/Id/GuidCombGenerator.cs) is doing this for GuidCombi to solve fragmentation issues for Guids.

**Comment by tatarincev** [comment]
Our platform has 
We later will change primary key type  for all ours tables from nvarchar(128) to char(16). 
and currently platform has VirtoCommerce.Platform.Data.Infrastructure.Interceptors.EntityPrimaryKeyGeneratorInterceptor type respond to generate primary key for any database rows i think it similar to IIdGenerator  from NHibernate.

**Comment by artem-dudarev** [comment]
Not char(16), but varchar(32).

**Comment by mokchhya** [comment]
Why varchar(32)?

**Comment by artem-dudarev** [comment]
The current primary key generator uses Guid.NewGuid().ToString("N"), which takes 32 characters.

**Comment by mokchhya** [comment]
Why it can't be just uniqueidentifier type which just takes 16 bytes? Anyway why i has to be varchar(32) and not char(32) if you choose to take that char path?

**Comment by artem-dudarev** [comment]
If someone wish to use different primary key generator, like Int32.ToString() as sujested by @anwaramoon, then char(32) will still store 32 characters, adding whitespaces to the string representaion of the number. So instead of "12345" the database will contain "1235___________________________".

**Comment by anwaramoon** [comment]
I would like to see that VirtoCommerce allow us to change the default primary key, same way we can change in AspNet Identity model. When AspNet identity model was started it was forcing string as primary key as well but later on it has been changed. Now we can decide what type of primary key want.

Of course, VirtoCommerce data model is not small like AspNet Identity model but conceptually it is possible in future versions to support this kind of flexibility.

At the moment i have imported one store into VirtoCommerce and I have used sequentialId to generate id in SQL script for data import. In the code, I've replaced default Guid.NewGuid() with [GuidCombiGenerator](https://github.com/nhibernate/nhibernate-core/blob/master/src/NHibernate/Id/GuidCombGenerator.cs). Please let me know if this is usefull for others and if you want me to create a pull requesst.

Thanks

**Comment by tatarincev** [comment]
It looks awesome!
Please make push request to **dev** branch with name *GuidCombiPrimaryKeyGeneratorInterceptor* and *VirtoCommerce.Platform.Data.Infrastructure.Interceptors* namspace.
And  we will be able now to choose what primary key we can use (Guid or ShortGuid).
Like this
```C#
 new CatalogRepositoryImpl(_connectionStringName, new GuidCombiPrimaryKeyGeneratorInterceptor())

**Comment by anwaramoon** [comment]
Hi @tatarincev 

Thanks for your feedback. I have added this class but there are 44 references for EntityPrimaryKeyGeneratorInterceptor class. Do you want me to replace all of them to use new class GuidCombiPrimaryKeyGeneratorInterceptor as well? In my case, I'll be replacing EntityPrimaryKeyGeneratorInterceptor with GuidCombiPrimaryKeyGeneratorInterceptor completly but just want to double check what you want in the pull request.

Thanks

**Comment by tatarincev** [comment]
No not need replace exist just as additional interseptor.

**Comment by anwaramoon** [comment]
Thanks @tatarincev. Pull request created as advised.
