### ISSUE TITLE
 "Property", "PropertyId" are not filled in PropertyValue

### ISSUE THREAD

**Issue by zhangpeng-kooboo** [VirtoCommerce/vc-community#124]
1. I use GetByIds from IItemService to retrieve products
var products = _itemService.GetByIds(productIds, ItemResponseGroup.ItemLarge)

2. I try to retrieve the property values from product
var productPropertyValues = product.PropertyValues;

3. But "Property", "PropertyId" are not filled in productPropertyValues 
Could not be able to know if the property is Multilingual Y/N :(

**Comment by tatarincev** [comment]
Hi, this so-conceived by initial design you should load properties meta information separately as is done in CatalogModuleProductsController.Get method. But I see that this is not very convenient and clear and i thought better will  do it in one place in itemService and manage it by ResponseGroup.PropertyMetaInfo.
