### ISSUE TITLE
Could not add a property to category under Virtual catalog

### ISSUE THREAD

**Issue by zhangpeng-kooboo** [VirtoCommerce/vc-community#125]
1. http://demo.virtocommerce.com/admin#/workspace/catalog
2. Select "Clothing virtual (virtual)"
3. Select "Accessories" > right menu "Manage"
4. Add a property apply to this category
5. 500 error

**Comment by tatarincev** [comment]
Hi, thanks for you attention,
Categories in virtual catalog cannot have properties, this fact what you can add proeprties to category in virtual catalog is a UI bug.

**Comment by zhangpeng-kooboo** [comment]
Hi @tatarincev ,

Is it a bad idea to allow add properties for categories in virtual catalog?
What we are trying to do is following:
We create 8 catalogs (Supplier catalogs)
We create 3 virtual catalogs (Each virtual catalog assign to a store)
For each virtual catalog we create some categories and add link products under those categories which look very nice. We can easily combine products from different supplier catalogs into virtual catalog categories.

But we are missing to add properties under those virtual catalog categories :( or is there any other alternative solutions.

Kind regards,
ZhangPeng

**Comment by tatarincev** [comment]
Main reason why virtual categories does't have properties is because it may contains only product links  and you cannot set propeprty values for product link you only can do it for physical product which belong to physical catalog and category. Thats main reason why we not provide properties for virtual categories.
To better understanding you domain problem  can you explain me a situation  as the properties of the product depend on the store where it is sold?
If i sold TV for example,TV have some propeties (reslotion, size, brand etc) in which cases i should add new properties for diff stores?

**Comment by zhangpeng-kooboo** [comment]
Properties of the product are not depend on the store.

We are trying to show categories under virtual catalog on front-end, but we only have "Name" field and also not multilingual that's cause us some problems.

**Comment by tatarincev** [comment]
Multilingual name for product and categories solved this problem?

**Comment by zhangpeng-kooboo** [comment]
Sorry maybe I did not explain the issue clear enough :(

1. If you go to "http://demo.virtocommerce.com/admin#/workspace/catalog"
Select the virtual catalog "Clothing virtual (virtual)" as example
2. The store select this virtual catalog "Clothing virtual (virtual)"
3. We want to show categories (name + description) under this store on front-end
Accessories, Bags, Dresses, Jewelry, Woman shoes

Due to virtual catalog categories not allow to add category properties, we could not add a description property, and we could not translate the name due to we could not add a name property.

Products are fine they are linked products.

**Comment by tatarincev** [comment]
As i  understand :) Problem in virtual categories localization on storefront?

**Comment by zhangpeng-kooboo** [comment]
that is issue 1 :)
and could not have description :(

**Comment by tatarincev** [comment]
Return to my previous post, if system will provide avability to define displayName and description for products and categories in multiple languages, like it done  for properties, its solve you problem?

**Comment by zhangpeng-kooboo** [comment]
I think so, it will solve most of cases :+1:

**Comment by tatarincev** [comment]
https://github.com/VirtoCommerce/vc-community/issues/126
Is in our plans. Try to do it in next release.

**Comment by tatarincev** [comment]
Sorry me, i forgot you can add properties for virtual categories but only Category type. That fact what you got 500 is looks as  bug and we will fix it.

**Comment by tatarincev** [comment]
And more localization by using properties seems to me even more correct than multilingual fields on product and categories. Thanks for good case of properties usage.
