### ISSUE TITLE
UnityServiceLocatorAdapter dependencies resolving

### ISSUE THREAD

**Issue by HaythemJ** [VirtoCommerce/vc-community#128]
Hi,

I don't know if I can ask a technical question regarding Unity, but there is something that I did not unterstand. In the UnityServiceLocatorAdapter we have a dependency with unityContainer

      public UnityServiceLocatorAdapter(IUnityContainer unityContainer)
        {
            _unityContainer = unityContainer;
        }

I found where the ServiceLocator is Registered 

       protected virtual void ConfigureContainer()
         {
            this.Logger.Debug(Resources.AddingUnityBootstrapperExtensionToContainer);

            Container.RegisterInstance<ILog>(Logger);

            this.Container.RegisterInstance(this.ModuleCatalog);

            if (useDefaultConfiguration)
            {
                RegisterTypeIfMissing(typeof(IServiceLocator), typeof(UnityServiceLocatorAdapter), true);
                RegisterTypeIfMissing(typeof(IModuleInitializer), typeof(ModuleInitializer), true);
                RegisterTypeIfMissing(typeof(IModuleManager), typeof(ModuleManager), true);
            }
        }

But I did not understand how did unity reslove UnityServiceLocatorAdapter constructor parameter. I did not find any registration for the type IUnityContainer.

Could you please explain to me how unity did it?

Best Regards
H.J

**Comment by tatarincev** [comment]
Unity created type instances from reflection if not find it on direct registration map.

**Comment by HaythemJ** [comment]
Very strong.

Thanks for the support.

Best Regards
H.J

**Comment by HaythemJ** [comment]
Ah ok, for IUnityContainer references, Unity inject the instance of UnityContainer itself, since it is already registered at first place.
