### ISSUE TITLE
How to integrate with a erp or crm ?

### ISSUE THREAD

**Issue by six006** [VirtoCommerce/vc-community#129]
I want to use odoo erp as our enterprise management ,can you tell me sth how to do it!

**Comment by aartiomov** [comment]
Hi, can you provide us with more info what kind of integration are you going to implement?
What functionality and what is the level of integration you expect?
In order we could give you suggestions on how it could be implemented.

**Comment by six006** [comment]
Thanks !
I want to sync some data with odoo ,like "magento to odoo".
for example :Order ,Product ,Customer

**Comment by aartiomov** [comment]
VirtoCommerce has Azure API App that can be used to expose it's api to the other systems. That way Order, Catalog, Customer data can be passed to odoo.
Let me check what integration points odoo has if that is the right way to integrate with odoo. I'll be right back.

**Comment by aartiomov** [comment]
There is an odoo-connector
http://odoo-connector.com/
It can be used as another approach to implement integration between VirtoCommerce and Odoo.
I'll look at odoo-connector to see what are the integration points provided by the connector.
You can also find api exposed by VirtoCommerce here http://demo.virtocommerce.com/admin/docs/ui/index
and check if it can be used for integration as well.
