### ISSUE TITLE
front end seo url

### ISSUE THREAD

**Issue by six006** [VirtoCommerce/vc-community#131]
When I visit "http://demo.virtocommerce.com",then it redirect to "http://demo.virtocommerce.com/electronics",

I have two store
first store url is"http://stor1.mysite.com" ,bind catalog electronics;
the second is "http://store2.mysite.com" bind catalog clothing

when I  open first store url http://stor1.mysite.com,it  redirect to http://stor1.mysite.com/electronics,but I need the url is http://stor1.mysite.com/

**Comment by Andrew-Orlov** [comment]
Do you have a "vcf.store" cookie in your request/response for URL http://stor1.mysite.com?

**Comment by six006** [comment]
![1](https://cloud.githubusercontent.com/assets/5348170/11142718/78174e22-8a2a-11e5-8d7f-b93854addffa.jpg)
visit url http://store1.mysite.com/cell-phones
redirect to http://store1.mysite.com/electronics/cell-phones,how to do it ? I just nedd a url like http://store1.mysite.com/cell-phones

**Comment by six006** [comment]
http://demo.virtocommerce.com/collections  is correct ,when visit other catagory will add the storename
http://demo.virtocommerce.com/electronics/camcorders
