### ISSUE TITLE
How to send a email ?

### ISSUE THREAD

**Issue by six006** [VirtoCommerce/vc-community#133]
I want to config a email account ,when a user register, order notification,then  send a email to them,but I don't know  how to do it !

**Comment by EugeneOkhriemnko** [comment]
Hi, you can check what types of notifications is define in platform here:

![notifications_list](https://cloud.githubusercontent.com/assets/1429226/11177661/c1e07ce6-8c4f-11e5-8b49-49f12ee2f646.PNG)

For sending them you need create sendgrid account in azure for your accout, copy credentials and add them in notification section of platform settings:

![azure_sendgrid_account](https://cloud.githubusercontent.com/assets/1429226/11177857/3e43718e-8c51-11e5-8859-1560120a8eb7.PNG)

![sendgrid_settings](https://cloud.githubusercontent.com/assets/1429226/11177884/7570c81e-8c51-11e5-9297-02fe03ff1381.PNG)

Creating sendgrid account in azure you can check here: https://azure.microsoft.com/en-us/documentation/articles/sendgrid-dotnet-how-to-send-email/

If you need information about creating new types of notification in platform I can write about it. Now we don't have documentation about notifications yet. It will be added soon.

**Comment by six006** [comment]
Thanks a lot! 
I discover it from code source and it can only be send by SendGridMessage method,I need to send a email with enterprise mail account ,for example, hi@mycompany.com!

I found the denpendency injection on Startup.cs

            container.RegisterInstance<IEmailNotificationSendingGateway>(emailNotificationSendingGateway);
            container.RegisterInstance<ISmsNotificationSendingGateway>(defaultSmsNotificationSendingGateway);


Is there any way I can override the method such as send email or sms , 
implement the interface IEmailNotificationSendingGateway or ISmsNotificationSendingGateway
with my custom class!


![3](https://cloud.githubusercontent.com/assets/5348170/11179246/0519386c-8c8d-11e5-9f0a-ba61f2dc7d61.jpg)
![2](https://cloud.githubusercontent.com/assets/5348170/11179256/10787920-8c8d-11e5-93e1-e336b122b3fe.jpg)

**Comment by EugeneOkhriemnko** [comment]
You can create your own implementation of IEmailNotificationSendingGateway or ISmsNotificationSendingGateway and register them in your module in PostInitialize method. We had create new email gateway based on SmtpClient, it will be released soon.

**Comment by six006** [comment]
Thanks again !
