### ISSUE TITLE
Content Module - fail to save multiple items - bug in MenuLinkList.Attach

### ISSUE THREAD

**Issue by anwaramoon** [VirtoCommerce/vc-community#134]
When saving multiple items in link list MenuLinkList.Attach method is over writing link list items due to a bug. Problem here is in the if condition inside for loop. For all new items we do not have any id. So for first iteration we add one item with no id in the list. For rest of the iterations we keep going into else block and overwriting first item. I have fixed it by adding a check for link.id. If link.id is null or empty than we should always add. Below is the fix. 

Please advise if this is acceptable fix and you want me to create a pull request.

#Fix

```
public void Attach(MenuLinkList list)
        {
            this.Name = list.Name;
            this.Language = list.Language;

            foreach (var link in list.MenuLinks)
            {
                if (string.IsNullOrEmpty(link.Id) || !this.MenuLinks.Any(l => l.Id == link.Id))
                {
                    this.MenuLinks.Add(link);
                }
                else
                {
                    var existingLink = this.MenuLinks.First(l => l.Id == link.Id);
                    existingLink.Url = link.Url;
                    existingLink.Title = link.Title;
                    existingLink.IsActive = link.IsActive;
                    existingLink.Priority = link.Priority;
                }
            }
        }
```

**Comment by tatarincev** [comment]
Thanks for help. Sure you can make pull request, please only to Dev branch.

**Comment by Woland2k** [comment]
Also before you create a pull request, make sure you sign the contributor agreement: http://virtocommerce.com/contribute-agreement

**Comment by anwaramoon** [comment]
Thanks @tatarincev  and @Woland2k. I have signed the agreement and created the pull request. 

One question, which branch do you recommend for personal commits dev or master? Any advise on contribution and best practices will be much appreciated.

Thanks

**Comment by Woland2k** [comment]
Thanks for signing the agreement and creating a pull request. The best place is dev branch.
