### ISSUE TITLE
VirtoCommerce.Platform.Core.Modularity.AssemblyResolver what for?

### ISSUE THREAD

**Issue by HaythemJ** [VirtoCommerce/vc-community#137]
Hi,

I cannot figure why the AssemblyResolver  is for? Since in the OwinStartup you already resolve the assemblies stored and collected in the Modules folder.

Best Regards
H.J

**Comment by Woland2k** [comment]
I believe it was done to add ability to resolve DLLs from folders other than /bin. This is used for instance when VC is installed as a single website (both frontend and admin sites), which is a requirement for MS Web Platfrom Installer. Our admin site is located in the subfolder within a frontend and DLLs are loaded when admin section is accessed. 

I assigned this to developer reponsible for that functionality, so he can give a more precise answer.
