### ISSUE TITLE
Documents related to catalog module

### ISSUE THREAD

**Issue by mokchhya** [VirtoCommerce/vc-community#138]
I could not find any document on catalog module on dev guide. Do you guys have link to docs(overview/detail) related to catalog module ? What is the difference between virtual and non virtual catalog? Is there any link between the two?

**Comment by Woland2k** [comment]
If you want to learn more about catalogs, look at the user guide: http://docs.virtocommerce.com/display/vc2userguide/8.+Merchandise+Management. It explains what those are and the differences.
