### ISSUE TITLE
Question: cloudfare and storefront experiene

### ISSUE THREAD

**Issue by anwaramoon** [VirtoCommerce/vc-community#140]
Hi,

Has anyone used cloudfare with store front? Would you able to share your experience? Is it recommended to use cloudfare or any similar service to speed up website?

Thanks
Anwar

**Comment by EugeneOkhriemnko** [comment]
Hi, in 2.5 version we using themes that has all main js/css itself. In 2.6 version we try to use cloudfare. It is not big raise of speed up when we testing your site locally, but it gives us normal speed up when we making stress testing. We will use cloudfare or other cdns in our next version of storefront.

**Comment by anwaramoon** [comment]
Thanks @EugeneOkhriemnko. Please do post or blog your experience about using cloudfare. It would be nice to see some stats that how much difference will it make. 

I have seen cdn usage in material theme for clothing store in past but may be for images only. I have just tried to check this in [demo site](http://demo.virtocommerce.com/clothing) but default theme has changed. Are we dropping material theme now? In version 2.6 is it going to be something similar in default theme? Are there any changes already made in dev branch which I can play with?

thanks

**Comment by tatarincev** [comment]
Thank you for your interest in the future of our product. 
Sure we will write some article in our blog about CDN and cloudfare when will have some practical expirience with it.

About our plans, now we are working on new Storefront implementation (dev-storefront branch)  it will contains initially one base (liquid electronic - Thimber) theme but we try to migrate also Matherial theme if will have enought time. Below short list of new storefront key features
* New **Clear** storefront code arhitecture and theme development process
* angularjs checkout, user cabinet and product detail views
* support both liquid and razor view engines
* full Shopify themes compatible
* full page caching and incredible perfomance
* loading js and css resources  from CDN and cloudfare css 
* Reviews, product comparison, prmotions and more more..

**Comment by anwaramoon** [comment]
Thanks @tatarincev. That sounds brilliant. All of the features you mentioned are very impressive. But that sounds like allot of work. Do you have any time frame for the new version? Will this be part of 2.6 or something like 3.0? 

Right now I am migrating one system to this platform. Your timeline will help me to decide whether I can fit new store-front with my time line or not. 

I am checking out dev-storefront branch and will play with it.  

I am more than happing to contribute. If I can be helpful in any kind please let me know.

**Comment by tatarincev** [comment]
Thanks, the best help for us is your feedback when implementing own solutions based on our platform.

**Comment by anwaramoon** [comment]
Of course. Do you have nay time frame for new store front?

**Comment by tatarincev** [comment]
I hope that we will release a 14.12.2015.

**Comment by anwaramoon** [comment]
Thanks @tatarincev. Looking forward to see this new store front.
