### ISSUE TITLE
When a Product has more than 1000 variations item records,backend is very slow!

### ISSUE THREAD

**Issue by six006** [VirtoCommerce/vc-community#141]
In our company ,we have many products ,and each product has more than 1000 variations ,when I open then product backend ,it's very very slow and load all variations of the product.

When I want to search a variation of a product ,I need to read from top to end with the scroll bar,
So I suggest that:
1: add some filting  on product variations by variation properties
2:add pagination on product  variation

**Comment by tatarincev** [comment]
Thanks for suggestion. We will consider your offer and  will try to optimize variation load time in next releases. Because currently implementation with huge amount of variations  It can cause problems.

**Comment by six006** [comment]
thanks ,It will be released on 2.6?

**Comment by tatarincev** [comment]
I think yes. If you have some another requrements and suggestions related to catalog functionality will glad to hear them.

**Comment by six006** [comment]
OK,thanks

**Comment by tatarincev** [comment]
Can you test perfomance with 2.6 version?
