### ISSUE TITLE
Discriminator column

### ISSUE THREAD

**Issue by cabri89** [VirtoCommerce/vc-community#142]
Hi everyone,
I don't really understand the purpose of the discriminator colum in EFRepositoryBase.
Does every table in Virto Commerce needs a discriminator column? even if only one type of entity is mapped to this table?

This is what I understand from the line 133 in EFRepositoryBase: 
  var config = modelBuilder.Entity<T>().Map(
              entity => entity.Requires(discriminatorColumn).HasValue(val).IsOptional());

It seems strange to me to have a discriminator column in the store table for example as only store entities goes there..

I've implemented a new entity and the according repository in the customer module.But the code first migrations doesn't include the discriminator column.

When querying my repository I get the following exception : 

Invalid Column Name "Discriminator"... I still don't understand why such a colmun would be needed as I only map one enttiy to the table.

Thank you for your help.

Regards,
Cabri89

**Comment by tatarincev** [comment]
Hi, you right we not use it anywhere now and this will be removed in next release.

**Comment by cabri89** [comment]
Thank you for your quick reply!
I'm waiting for the 2.6 release with impatience!
Keep up the good work!
Cheers
