### ISSUE TITLE
Question - DotLiquid optimization by Steve

### ISSUE THREAD

**Issue by anwaramoon** [VirtoCommerce/vc-community#143]
hello guys,

Is it possible to merge [Steve's](https://github.com/SteveLillis) optimization changes with VirtoCommerce/dotLiquid fork? May be for new store-front?

You can read about his changes [here](http://stevelillis.blogspot.co.uk/2015/01/optimising-dotliquid-part-1.html).

His fork link is https://github.com/SteveLillis/dotliquid.

Thanks

**Comment by Woland2k** [comment]
We integrated most of the changes Steve mentioned already. Especially things like compiled regular expressions and many others.

**Comment by anwaramoon** [comment]
Brilliant. Thx
