### ISSUE TITLE
single sign-on for VirtoCommerce and Orchard!

### ISSUE THREAD

**Issue by six006** [VirtoCommerce/vc-community#145]
I want to a extenstion single sign-on for VirtoCommerce and Orchard!

Like this extension Single Sign-On For Magento And WordPress
 http://codecanyon.net/item/single-signon-for-magento-and-wordpress/861453

**Comment by Andrew-Orlov** [comment]
Hi. Do you mean our Orchard-module or your own? In first case - our module is quite simple and was developed only for demo-purposes. Actually it has no any customer account functionality at all. In second case - we are implementing a new storefront logic right now and after that we can discuss your suggestion about integration VC and Orchard.
