### ISSUE TITLE
How to set the local language on the backend?

### ISSUE THREAD

**Issue by six006** [VirtoCommerce/vc-community#148]
I devleop the backend on the dev branch.
I create a new file " cn.VirtoCommerce.Platform.json" on the VirtoCommerce.Platform.Web/app_Data/Localizations and translate it ,
![1](https://cloud.githubusercontent.com/assets/5348170/11493687/3183401e-9836-11e5-9a7c-82718d0c6911.jpg)
![2](https://cloud.githubusercontent.com/assets/5348170/11493688/32f37482-9836-11e5-98ed-871f1294892e.jpg)

then set the local language as cn on VirtoCommerce.Platform.Web\Scripts\app\app.js,
![3](https://cloud.githubusercontent.com/assets/5348170/11493694/3a918ff8-9836-11e5-8d4a-b90da9ed2e87.jpg)

$translateProvider.useUrlLoader('api/platform/localization/locale')
        .useLoaderCache(true)
        .useSanitizeValueStrategy('escapeParameters')
        .preferredLanguage('cn')
        .fallbackLanguage('cn')
        .useLocalStorage();

but it still load the english resources ,
![4](https://cloud.githubusercontent.com/assets/5348170/11493703/45da107e-9836-11e5-986b-8a5b0bc0047a.jpg)

I don't know how to set a local language on the backend!

**Comment by six006** [comment]
I found that the source code param is local and give a default value "en"
![0](https://cloud.githubusercontent.com/assets/5348170/11494097/2759a566-983a-11e5-8f7f-232f9d62570e.jpg)

but the api request querystring name is lang
![1](https://cloud.githubusercontent.com/assets/5348170/11494109/389aacc6-983a-11e5-8a7f-961329b617f0.jpg)

http://dev.b.com/admin/api/platform/localization/locale?lang=cn

Is need to change the method parameter name from "local" to "lang"?

**Comment by six006** [comment]
I resovle the problem!
![1](https://cloud.githubusercontent.com/assets/5348170/11494202/1fd64456-983b-11e5-8557-b139515aec15.jpg)
![2](https://cloud.githubusercontent.com/assets/5348170/11494201/1fd61558-983b-11e5-8a1a-63d24030cdbe.jpg)

**Comment by tatarincev** [comment]
Thanks, litle misspeling in our api.
