### ISSUE TITLE
Localizations the word dialog lost a char  on account-api.js

### ISSUE THREAD

**Issue by six006** [VirtoCommerce/vc-community#149]
PLATFORM\VirtoCommerce.Platform.Web\Scripts\app\security\blades\account-api.js
line 39 
title: "platform.dialog.api-key-delete.title",
message: "platform.dialog.api-key-delete.message",

![1](https://cloud.githubusercontent.com/assets/5348170/11498164/b728ca78-9858-11e5-8d36-58b3e93f9419.jpg)
![2](https://cloud.githubusercontent.com/assets/5348170/11498163/b728468e-9858-11e5-906c-b1da9820eb40.jpg)
![3](https://cloud.githubusercontent.com/assets/5348170/11498162/b7224504-9858-11e5-9393-fdac0ad95223.jpg)

**Comment by Dmitry-virtoway** [comment]
Yes, you are right, should be "dialogs". 
Fix has been commited to the dev branch, try now.

**Comment by tatarincev** [comment]
As I understand it you translate manager resources into Chinese language.
Can I ask you to share resulting translation with our community?
