### ISSUE TITLE
How to use the property attribute?

### ISSUE THREAD

**Issue by six006** [VirtoCommerce/vc-community#153]
Hi,
I have a question ,how to use the property attribute?
I set two attributes for a property,but I don't know how to use them?
![1](https://cloud.githubusercontent.com/assets/5348170/11619579/9f2a1c0c-9ce4-11e5-80b4-f5d651d0c914.jpg)

**Comment by tatarincev** [comment]
**Property attributes** used for define additional  meta information for properties. And you can in future use these meta information in storefront or in your client code for as you wish.

**For example**: storefront properties grouping - you can add to you product properties attributes with name **Group** for each property and set  some values (Item specifics, Features, Form factor etc) and now you have ability to read these attributes in storefront code within properties and display its in tab control.
We currently use attributes for store properties multilingual display names.

**Comment by six006** [comment]
Are there any example in the demo data and frontend

**Comment by tatarincev** [comment]
Only for property name localization.

**Comment by six006** [comment]
thanks
