### ISSUE TITLE
Can't save when add a item to pricelist 

### ISSUE THREAD

**Issue by six006** [VirtoCommerce/vc-community#154]
I want to choose a pricelist and then add some product item in it.But when I click save button it does't work! 
![1](https://cloud.githubusercontent.com/assets/5348170/11620461/1fd7f4c4-9cee-11e5-996c-262fe0a12596.jpg)
![2](https://cloud.githubusercontent.com/assets/5348170/11620462/20105670-9cee-11e5-9c57-c401bf05a867.jpg)
![3](https://cloud.githubusercontent.com/assets/5348170/11620463/2031a956-9cee-11e5-999d-06691ffbe9c5.png)

**Comment by eMazeika** [comment]
The idea is that you should manage prices in this UI. You've added a product but left it without a price. Click the product to add 1 or more prices and click "save" when you are done with all the products.
How could we improve the UX (user experience) in here? Maybe add some warning message after "Save" was clicked?

**Comment by six006** [comment]
thanks
