### ISSUE TITLE
Can't add 'New publishing element' on marketing Dynamic content

### ISSUE THREAD

**Issue by six006** [VirtoCommerce/vc-community#156]
Can't save anything on the name field when the textbox lost focus!

![1](https://cloud.githubusercontent.com/assets/5348170/11623449/efa9f77e-9d07-11e5-9a1f-32caae880722.jpg)

![1](https://cloud.githubusercontent.com/assets/5348170/11623401/a3a931aa-9d07-11e5-873f-8d356ee388eb.jpg)

**Comment by six006** [comment]
I found the solution
The name is auto generated by combinatin of placehoders and content items.
1.Click 'Add Content publishing'
![1](https://cloud.githubusercontent.com/assets/5348170/11623727/bc87a4ac-9d09-11e5-8fc2-fd5dee32b3e5.jpg)

2.Set the Placeholders or Set the Content items the name will auto generate
![2](https://cloud.githubusercontent.com/assets/5348170/11623735/c9de3224-9d09-11e5-9cd5-ef4c9dc647e4.jpg)

**Comment by six006** [comment]
it seems like can's edit the name

**Comment by six006** [comment]
When I add a publishing content ,how to used them in the frontend ?

**Comment by tatarincev** [comment]
You can read how to use dynamic content placeholders for storefront 2.5 version here
http://docs.virtocommerce.com/display/vc2userguide/Registering+Content+Placeholders
In future 2.6 release this function  will be changed.

**Comment by six006** [comment]
thanks a lot
