### ISSUE TITLE
NopCommerce data export to VirtoCommerce problem

### ISSUE THREAD

**Issue by six006** [VirtoCommerce/vc-community#158]
Our team develop b2c project using NopCommerce for 3 years,
Now want to build b2b solution with VirtoCommerce.

We found some problems 
1:Product Detail Description can't found on the virtocommerce.
2.We can edit the detail  with tinyeditor  in nop,but in virtocommerce the editor is simple ,our administatrator don't work efficiency.
3.Product Variant search is very simple.If we have 1000 product varations,the backend is very slow.
4.Can give a solution export data from nop to virtocommerce when the data is large,such as 100,000 products varations.

**Comment by tatarincev** [comment]
Thank you for your confidence in our product.
1. we use for product descriptions  **Editorial review** 
![image](https://cloud.githubusercontent.com/assets/7566324/11652716/f8d94fee-9da1-11e5-82b3-64066551eab3.png)

2. We currently use [textAngular](https://github.com/fraywing/textAngular) and [ui-codemirror](https://github.com/angular-ui/ui-codemirror) editors. You can use preffered for you editors (though you should will make little ui changes).

3. In next release we try to fix this perfomance issue. (can you send me some sample your products with 1000 variations for test)

4. Currently we have CSV import to catalog. But we never testing it with huge amount data and I afraid here will be some problems with perfomance. You can split you catalog to multiple CSV chunks and try to import by small parts or you can implement  own [catalog import extension](http://docs.virtocommerce.com/display/vc2devguide/Creating+catalog+custom+import-export+extensions) and import data using by it.

**Comment by six006** [comment]
thanks
