### ISSUE TITLE
How to debug a managed module

### ISSUE THREAD

**Issue by HaythemJ** [VirtoCommerce/vc-community#163]
Hi,

How to debug a managed module? I tried to add .PDB file but cannot step into function call.

Best Regards
H.J

**Comment by Woland2k** [comment]
Please checkout this issue: https://github.com/VirtoCommerce/vc-community/issues/135, it exlains how to debug a module.

**Comment by HaythemJ** [comment]
Hi,

Thank you. I made it as simple as:

1/ Build project on Debug Mode (not Active(Debug))
2/ Load assemblies to Appdomain with .pdb files via Assebly.Load(byte[] dll, byte[] pdb)

Best Regards
H.J

**Comment by Woland2k** [comment]
Seems more complex than needed, all you need to do is build whole solution in debug mode and then attach to IIS process to debug.
