### ISSUE TITLE
Question - Is there anyway to set shippment charges by order amount?

### ISSUE THREAD

**Issue by anwaramoon** [VirtoCommerce/vc-community#167]
Hi,

Is there any option to set shippment charges by order amount? I have seen only fixed rate shipmment module which allow you to set fix charges for each order. I have a requirement where shippment charges needs to be changed by order value. For instance, if order is less than £50.00 than £6.00 is shippment charge. All orders above £50.00 is free. 

Thanks

**Comment by tatarincev** [comment]
You can use for this purposes Promotions from Marketing module which allows you to determine the promotions  for delivery depending on certain conditions (example cart total greater that 100 USD)

**Comment by anwaramoon** [comment]
Thanks @tatarincev. This is working great after fixing a small bug in store front. Please see #171 for new store front bug detail.
