### ISSUE TITLE
New Storefront - Creating order is not saving customer infomration and delivery address

### ISSUE THREAD

**Issue by anwaramoon** [VirtoCommerce/vc-community#168]
Steps:-

1. Add items into basket
2. Goto checkout
3. Login using existing account
4. Select fix rate shipping method
4. Select manual test payment method
5. Complete order

<img width="906" alt="create_order_missing_customer_info" src="https://cloud.githubusercontent.com/assets/1743538/11766814/99bdf9be-a18f-11e5-81d6-141cd3b9d5ef.PNG">

**Comment by Andrew-Orlov** [comment]
Username of shopping cart and order is: "Anonymous" for anonymous and first and last name for registered customer for now. Order addresses bug was fixed too.
