### ISSUE TITLE
Store Manager - Customer Orders enhancements

### ISSUE THREAD

**Issue by anwaramoon** [VirtoCommerce/vc-community#169]
Hi,

Are there any enhancements planned for customer orders in store manager? I am looking for following options.

1. Filters - filter by date, customer, order status, payment status, shippment status etc
2. Print - print complete order, print packaging/shippment receipt, print customer invoice etc

If nothing is planned than can you please provide some guideline for the implementation.

Thanks

**Comment by tatarincev** [comment]
Hi, we do not have any filtration functionality in Manager UI. (it open task). If you have some idea we will glad to hear it.
Printing also missed but I think you can use some already exist PDF libraries like this http://sourceforge.net/projects/itextsharp and make service for PDF generation with resulting report downloading from ui. Or use more advanced services like a Microsoft Power BI which provided more flexible and powerfull tools for you data analyse and report printing. Here you can read more how to integrate VirtoCommerce  with popular data analyses services http://docs.virtocommerce.com/display/vc2devguide/Reporting

**Comment by anwaramoon** [comment]
Hi @tatarincev, thanks for your feedback. I've created a sample mock for adding filters on customer orders grid. Please see below example mockup. I have tried to cover maximum filters. Obviously you can add many more and create the UI differently. But I am just trying to show what I am thinking.

![order filters mock](https://cloud.githubusercontent.com/assets/1743538/11768760/5cc36442-a1ce-11e5-84a1-a3de4c8a834d.png)

I'll have a look into Microsoft Power BI. But I am more looking into adding one more buttons in the blade bar to print document just to provide some basic printing options. Indeed Power BI can be used for reporting and shipstation can be used for shippment. But I would like to see some basic printing and shipment features in the platform. Perhaps a shippment module as well. :) 

![print document](https://cloud.githubusercontent.com/assets/1743538/11768782/5b957640-a1cf-11e5-8374-99c1dea85165.jpg)

Please let me know your thoughts and anything I can do. 

Thanks

**Comment by tatarincev** [comment]
Thanks @anwaramoon use blades for filtration option is a good idea.
Recently we will star new scrum sprint and one of possible sheduled task may be  filtration UI in manager. 
For built-in printing need implement special API which generate PDF by using some external library and returned download link to UI. I this case UI will be very simple and main work will do in backend code. I can not promise that we will soon be able to do this function because it very complex to make realy generic implementation.

**Comment by anwaramoon** [comment]
Thanks @tatarincev for looking into filtering. I am aware generic printing may not be easy. I just need very basic printing options for packaging, shipment, invoice and order. I'll try to add some basic printing options myself and will show you once finished. If you like it and find it useful for community than i'll create a pull request otherwise i'll just keep it in my fork. thanks

**Comment by Woland2k** [comment]
The best and easiest option will be to use reporting, aka reporting services to create these PDFs.
