### ISSUE TITLE
New Storefront - Payment due currency is wrong on checkout

### ISSUE THREAD

**Issue by anwaramoon** [VirtoCommerce/vc-community#170]
Checout screen is showing wrong payment due currency. However, currency symbol is correct.

<img width="1001" alt="payment_due_currency_wrong" src="https://cloud.githubusercontent.com/assets/1743538/11767955/16ba176a-a1b6-11e5-83af-8ae986a0086e.PNG">

**Comment by Andrew-Orlov** [comment]
Well, this label is actually unnecessary. Removed it.

**Comment by anwaramoon** [comment]
Perfect. Its gone now. Thanks
