### ISSUE TITLE
Store Manager - Customer module : organization details is not the checked organization.

### ISSUE THREAD

**Issue by cabri89** [VirtoCommerce/vc-community#174]
Hello,

In the customer module when checking an organization and clicking on the manage button, the information on the details blade is the data of the selected organization (in blue) and not the checked organization.

Thank you for your help.

Regards,
Cabri89

**Comment by eMazeika** [comment]
Thanks for reporting this intricacy. We've redesigned the way of working with lists recently and you'll see it fixed in the upcoming version 2.6 release. (There will be no more "Manage" button in the toolbar.)
Meanwhile you could use the context menu to open the correct organization.

**Comment by cabri89** [comment]
Thanks.
