### ISSUE TITLE
New Storefront - MenuLink converter - object refrence exception

### ISSUE THREAD

**Issue by anwaramoon** [VirtoCommerce/vc-community#178]
I am getting object reference exception in menu link converter when menu links property is null. 

```csharp
webModel.MenuLinks = serviceModel.MenuLinks.Select(ml => ml.ToWebModel(urlBuilder)).ToList();
```

Following fix is working for me. Please let me know if this needs a pull request.
```csharp
webModel.MenuLinks = serviceModel.MenuLinks != null ? serviceModel.MenuLinks.Select(ml => ml.ToWebModel(urlBuilder)).ToList() : new System.Collections.Generic.List<MenuLink>();
```

**Comment by Andrew-Orlov** [comment]
I've already fixed this bug but planed to commit it as part of bigger changes. Well, this issue is fixed. Thanks for your help.

**Comment by anwaramoon** [comment]
Great. Thanks
