### ISSUE TITLE
Cart lagging issues

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-community#179]
In 2.6 cart is implemented using angularjs in such a way that from UX prospective UI lags. For example when I go to the cart and want to increment the number of items in the cart, I click plus and nothing happens (under the hood, web pages submists requests and on success changes the value and updates all the prices) and only after a few seconds UI is updated. The more ideal scenario will be: when I click plus, the value is instantly updated and a small text message or git appear notifying me that something is updating.

The same behaviour should be done for when removing item in the cart, item should be instantly removed.

**Comment by Andrew-Orlov** [comment]
Done.
