### ISSUE TITLE
Mobile app starter app

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-community#188]
Develop starter app that demonstrates using Virto Commerce to develop mobile application using either Ionic or Onset Corbin framework with angularjs.

As part of the prototype create a point of sale application.

**Comment by six006** [comment]
very good

**Comment by anwaramoon** [comment]
Ionic is great framework. I have used it in one mobile app. It also uses angular so less learning curve for the rest. I would recommend using Ionic with cordova to package the app as native app.

**Comment by Woland2k** [comment]
yes, we are using Ionic with crodova.

**Comment by samdubey** [comment]
+1 for IonicFramework

**Comment by Woland2k** [comment]
Here are some pictures of mobile starter app working using our web services:

![11mob-checkout-thanks](https://cloud.githubusercontent.com/assets/1566470/12567693/7407602c-c375-11e5-97cc-8d5fc6314050.PNG)
![10mob-checkout-payment](https://cloud.githubusercontent.com/assets/1566470/12567699/7428a1e2-c375-11e5-8f33-dfa2ec5adb96.PNG)
![09mob-checkout-shipping](https://cloud.githubusercontent.com/assets/1566470/12567697/742618b4-c375-11e5-9952-60d5cf3b490a.PNG)
![07mob-cart](https://cloud.githubusercontent.com/assets/1566470/12567695/7424ae52-c375-11e5-9a9d-0f89210fcb24.PNG)
![08mob-checkout-address](https://cloud.githubusercontent.com/assets/1566470/12567700/74320b6a-c375-11e5-986f-5e5d38956d67.PNG)
![05mob-item-detail](https://cloud.githubusercontent.com/assets/1566470/12567698/74274612-c375-11e5-9f9a-d57d9e063bee.PNG)
![06mob-item-detail-variation](https://cloud.githubusercontent.com/assets/1566470/12567696/7425df84-c375-11e5-8133-a7872735176a.PNG)
![04mob-category-items](https://cloud.githubusercontent.com/assets/1566470/12567694/741ca11c-c375-11e5-87cf-56099cceefbf.PNG)
![03mob-home-menu](https://cloud.githubusercontent.com/assets/1566470/12567701/743ba8be-c375-11e5-9168-bf64a852c760.PNG)
![02mob-home](https://cloud.githubusercontent.com/assets/1566470/12567702/743d4b24-c375-11e5-8408-2b84a23fc5a5.PNG)
![01mob-login](https://cloud.githubusercontent.com/assets/1566470/12567703/743ef654-c375-11e5-8597-29e6a404358e.PNG)
