### ISSUE TITLE
Stock Management intermittence

### ISSUE THREAD

**Issue by IT4Solution** [VirtoCommerce/vc-community#19]
Hi everyone! 

Hello.
I tested several times in same scenario (store, logged user, variation of product) and sometimes the 'In Stock Quantity' decreases, sometimes not.
I think I found the problem but I don't know the solution.
Sometimes the Inventory Repository does not loads properly (count = 0), then the repo.UnitOfWork.Commit() returns false (0). If I keep trying backing the debug to the point of 'catalogHelper' loading, the operation is successful.
it may be an Injection failure?

![inventoryrepository](https://cloud.githubusercontent.com/assets/10602250/5805806/74cce5c2-9ff9-11e4-815b-5d178766da7c.png)

                var catalogHelper = new CatalogClient(CatalogRepository, null, CustomerSessionService, CacheRepository, InventoryRepository);
                var item = catalogHelper.GetItem(lineItem.CatalogItemId);
                if (item != null && item.TrackInventory)
                {
                    var repo = InventoryRepository;
                    var inventory = catalogHelper.GetItemInventory(lineItem.CatalogItemId, lineItem.FulfillmentCenterId);
                    if (inventory != null)
                    {
                        if (AdjustStockInventoryQuantity(lineItem, inventory))
                        {
                            repo.UnitOfWork.Commit();
                        }
                        else
                        {
                            throw new InvalidWorkflowException(string.Format("Failed to adjust inventory for lineItem {0}", lineItem.LineItemId));
                        }
                    }
                }

**Comment by Woland2k** [comment]
Thanks for reporting the issue here!

**Comment by adomass** [comment]
Hi,It seems that it was a cache issue. Invetory was retrieved from cache and it was deattached from repository. The solution is to retrieve item directly from repo not from cache.

Here is  my fix checkin in dev branch:
https://github.com/VirtoCommerce/vc-community/commit/173bf4757d6793d957230227da12287393908f1c
