### ISSUE TITLE
Move category title to correct place and remove duplicate

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-community#190]
How it is now:
<img width="886" alt="screen shot 2015-12-21 at 1 33 57 pm" src="https://cloud.githubusercontent.com/assets/1566470/11941900/91c5aa50-a7e7-11e5-8c5e-18117de3896b.png">

How it should be:
<img width="900" alt="screen shot 2015-12-21 at 1 35 32 pm" src="https://cloud.githubusercontent.com/assets/1566470/11941925/be2f93da-a7e7-11e5-9ab6-e66f34bbeb45.png">

**Comment by Andrew-Orlov** [comment]
Fixed.

**Comment by Woland2k** [comment]
The error is not about duplication but rather location of the header element.

**Comment by Andrew-Orlov** [comment]
The markup of collection header is kept from original theme. There is a condition: if collection has description it will be rendered like "How it is now", if not - "how it should be". So to collection description was populated with collection name.
