### ISSUE TITLE
Cart popup doesn't open when in mobile reponsive view

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-community#191]
Simply minimize browser to mobile size and press cart button -> nothing happens

**Comment by Andrew-Orlov** [comment]
Fixed in dev branch. Cart popup is responsive for any screen resolutions and document will be scrolled to top after pressing "Add to cart" button.

**Comment by Woland2k** [comment]
Still doesn't work in the current demo.

**Comment by Andrew-Orlov** [comment]
Did you try to reapply theme for store?

**Comment by Woland2k** [comment]
This is the site: http://demo.virtocommerce.com/Electronics/en-US/

**Comment by Andrew-Orlov** [comment]
Accept the cart popup issue with Chrome.

**Comment by Andrew-Orlov** [comment]
Fixed.
