### ISSUE TITLE
Default theme frontend issues

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-community#195]
When in mobile view, list displayed over the menu choices.
Menu drop downs don't work and can't be selected as they disappear.
Slider is not correct width, has no way to switch between views and no left or right arrrows (use default slider)
Remove top section that displays: "FREE GROUND SHIPPING" ...
Product display page doesn't display: "WE ALSO RECOMMEND" section at the bottom

**Comment by Andrew-Orlov** [comment]
Fixed.
