### ISSUE TITLE
How to support C#6.0 in vs2013

### ISSUE THREAD

**Issue by six006** [VirtoCommerce/vc-community#197]
Hi ,I download the virtocommerce2.6 release ,and compile the solution but it return some error,at last I find some new C#6.0 sytax in the source code.

I don't want to download the vs2015 ,how to develop virtocommerce with c# 6.0 in vs2013!

**Comment by Woland2k** [comment]
Yes, I agree we need to make it compatible with vs2013, shouldn't be a problem however.

**Comment by tatarincev** [comment]
Be patient we will remove C# 6.0 operators from code  in dev branch today and you  can use dev branch version without VS update.

**Comment by six006** [comment]
OK,thanks!

**Comment by qq550723504** [comment]
When do you celebrate Christmas day?

**Comment by Woland2k** [comment]
We celebrate on the 25th in US office, in others on different days.
