### ISSUE TITLE
Clothing store login without a password input

### ISSUE THREAD

**Issue by qq550723504** [VirtoCommerce/vc-community#198]
![1](https://cloud.githubusercontent.com/assets/6007227/11972597/7bb92e32-a989-11e5-8281-880202dee5d0.png)
![qq 20151223152627](https://cloud.githubusercontent.com/assets/6007227/11972605/8f00185c-a989-11e5-9bb7-2b0840e20bd4.png)

**Comment by Andrew-Orlov** [comment]
Fixed.
