### ISSUE TITLE
2.6 storefront bugs&features

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-community#199]
* CartСontroller add some methods to add item to cart by index (need for shopify themes compability)
* Account orders list corrupted makeup (css)
* Clothing theme filters not working
* Cart popup UX bug when quick incerease quantity
* Add to cart item time lag when click add to cart button
* Related products dissapears
* Fix slider (width should align correctly)
* Remove free shipping dynamic content from homepage

**Comment by Andrew-Orlov** [comment]
Added Shopify methods to cart controller, fixed cart popup

**Comment by Andrew-Orlov** [comment]
Related products (products from the same category) on product page will be displayed for now.
