### ISSUE TITLE
There are two  C#6.0 sytax still exits in the sourcecode

### ISSUE THREAD

**Issue by six006** [VirtoCommerce/vc-community#208]
First ":\PLATFORM\Modules\Search\VirtoCommerce.SearchModule.Data\Services\CatalogItemIndexBuilder.cs"
line 62 : throw new ArgumentNullException(nameof(partition));
![Uploading 1.jpg…]()

Second:"\STOREFRONT\VirtoCommerce.LiquidThemeEngine\Filters\UrlFilters.cs"
line 315  label += $" ({tag.Count})";

![2](https://cloud.githubusercontent.com/assets/5348170/12015724/9a06c1a6-ad7b-11e5-9dd2-75e4a411e8d6.jpg)

**Comment by tatarincev** [comment]
Just 1 min will fix.
