### ISSUE TITLE
There are 7 C#6.0 sytax still exits in the storefront sourcecode

### ISSUE THREAD

**Issue by six006** [VirtoCommerce/vc-community#211]
/STOREFRONT/VirtoCommerce.LiquidThemeEngine/Objects/ItemCollections.cs
line9 public IList<T> Root { get; } 

/STOREFRONT/VirtoCommerce.LiquidThemeEngine/Objects/Tag.cs
line9   public string GroupName { get; }
line14 public string Value { get; }
line15 public string Id { get; }

/STOREFRONT/VirtoCommerce.Storefront/Builders/CartBuilder.cs
line9   cart.CustomerName = $"{_customer.FirstName} {_customer.LastName}";
line19 return $"Cart-{storeId}-{customerId}";

/STOREFRONT/VirtoCommerce.LiquidThemeEngine/Filters/UrlFilters.cs
line9  label += $" ({tag.Count})";

**Comment by six006** [comment]
missing get method in the property when compile the sourcecode

**Comment by tatarincev** [comment]
What wrong in ?
/STOREFRONT/VirtoCommerce.LiquidThemeEngine/Objects/ItemCollections.cs
line9 public IList Root { get; }

/STOREFRONT/VirtoCommerce.LiquidThemeEngine/Objects/Tag.cs
line9 public string GroupName { get; }
line14 public string Value { get; }
line15 public string Id { get; }

**Comment by tatarincev** [comment]
Ok I see missed set.

**Comment by tatarincev** [comment]
Done.

**Comment by six006** [comment]
thanks
