### ISSUE TITLE
Storefront "Store URL" setting does't work!

### ISSUE THREAD

**Issue by six006** [VirtoCommerce/vc-community#212]
Currently I use the dev brach in version 2.6.1107.

I want to display my store using the sub domain such as  http://store1.xxx.com, http://store2.xxx.com
but when I save the Store Url on Store Advanced properties,it does't work on the frontend.
I found that  it can only work at the sub folder such as http://xxx.com/store1, http://xxx.com/store2.

![1](https://cloud.githubusercontent.com/assets/5348170/12016855/071dca0a-ad8b-11e5-8b83-5e5ae8abcef3.jpg)
![2](https://cloud.githubusercontent.com/assets/5348170/12017141/1410e690-ad8e-11e5-8b09-9a9d4d4a35c3.jpg)
![3](https://cloud.githubusercontent.com/assets/5348170/12017166/6664a6ac-ad8e-11e5-9aca-f4fa4ee8d312.jpg)
![4](https://cloud.githubusercontent.com/assets/5348170/12017167/6669754c-ad8e-11e5-99d4-59503f01de07.jpg)
![5](https://cloud.githubusercontent.com/assets/5348170/12017168/666a963e-ad8e-11e5-8fa1-29f5efbeda5d.jpg)
![6](https://cloud.githubusercontent.com/assets/5348170/12017169/669842c8-ad8e-11e5-9f6a-fffb63f72890.jpg)

**Comment by tatarincev** [comment]
Can you check what you save this urls for stores?
