### ISSUE TITLE
How to add assets to catalog products

### ISSUE THREAD

**Issue by Piusn** [VirtoCommerce/vc-community#22]
I am not sure if I am doing it the wrong way. On my sample azure hosted virto commerce I am trying to add images for a product but they are not showing.

Second the catalog folder is not showing on the list of folders when I am uploading.
Which is the best procedure to add images and thumbnails to products.?

**Comment by eMazeika** [comment]
make sure to set 'primaryimage' value for Group name while adding the image. 
Then update the search index: Settings -> Search, select "catalogitem" and click 'REBUILD'.

> Second the catalog folder is not showing on the list of folders when I am uploading.
Can you explain this problem in detail?

> Which is the best procedure to add images and thumbnails to products.?
You can upload image files to file storage in advance, using some third party tool. Group them by code or item name, then assign images to each item using Commerce Manager.

**Comment by Piusn** [comment]
Done so but the status remains "Never started"

**Comment by Woland2k** [comment]
In order for it to start, you need to either have azure scheduler worker role to run or run a frontend website which has built in scheduler when running as an azure website. How did you setup VC?
