### ISSUE TITLE
Microsoft Web Gallery Still shows 2.5 version need update to 2.6

### ISSUE THREAD

**Issue by samdubey** [VirtoCommerce/vc-community#224]
Dear Team,

Microsoft Web Gallery needs to be updated for VirtoCommerce for 2.6 version
https://www.microsoft.com/web/gallery/virtocommerce.aspx

**Comment by Woland2k** [comment]
Yes, we are aware and working on the package to submit to MS.

**Comment by samdubey** [comment]
Thanks
