### ISSUE TITLE
Running VirtoCommerce CommerceManager resulting into Error

### ISSUE THREAD

**Issue by samdubey** [VirtoCommerce/vc-community#225]
Running VirtoCommerce CommerceManager resulting into Error

http://localhost:61141/#/sampleDataInitialization

Error resolving type specified in JSON 'VirtoCommerce.CatalogModule.Web.Security.CatalogSelectedScope, VirtoCommerce.CatalogModule.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Path 'Users[5].Roles[1].Permissions[0].AssignedScopes.$values[0].$type', line 102, position 180.
 Could not load assembly 'VirtoCommerce.CatalogModule.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

![error](https://cloud.githubusercontent.com/assets/4013722/12115249/86a16650-b3d6-11e5-9400-78db7be7f394.png)

**Comment by tatarincev** [comment]
Which version of manager you use? Make sure you correctly mapped Modules folder in IIS. And rebuilded whole solution.

**Comment by samdubey** [comment]
Done
Working now :-)
