### ISSUE TITLE
CMS prevent using illegal chars in pages and template names

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-community#230]
![image](https://cloud.githubusercontent.com/assets/7566324/12230012/c1106984-b855-11e5-82a2-ae8e3a91f96c.png)

**Comment by eMazeika** [comment]
what characters to allow?

**Comment by tatarincev** [comment]
http://stackoverflow.com/questions/6745405/how-to-make-filenames-web-safe-using-c-sharp

But rely needs to redesign CMS UI module because on current implementation I can't able to replace file name without user confirmation.
