### ISSUE TITLE
Error Azure deployment

### ISSUE THREAD

**Issue by kodermax** [VirtoCommerce/vc-community#24]
I got error, when i deployed to azure on the Visual Sutdio 2013
![erorr](https://cloud.githubusercontent.com/assets/590985/5886689/5ccfd3ea-a3bd-11e4-98b9-269e6bc7d0d2.png)

**Comment by IgorisB** [comment]
StoreWebApp.csproj has remaining parts for older version of visual studio. Remove following things from this file:
1) remove this "PropertyGroup" section:   
<PropertyGroup>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">10.0</VisualStudioVersion>
    <VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
  </PropertyGroup>

2) remove Condition="false" from the line:
<Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v10.0\WebApplications\Microsoft.WebApplication.targets" Condition="false" />


Please let me know if it helps.

**Comment by kodermax** [comment]
I have a new error
![error2](https://cloud.githubusercontent.com/assets/590985/5887820/75cf847e-a3f6-11e4-8a55-64186509c061.jpg)

**Comment by kodermax** [comment]
and also
![error3](https://cloud.githubusercontent.com/assets/590985/5887954/2c7340da-a3fc-11e4-9681-d25b4d102081.png)

**Comment by IgorisB** [comment]
It doesn't find java runtime files. Be sure you have JRE installed and JAVA_HOME environment variable is correctly set.

**Comment by kodermax** [comment]
my java_home
![1](https://cloud.githubusercontent.com/assets/590985/5890676/406eefd6-a478-11e4-9e07-97d5b6c65445.png)
