### ISSUE TITLE
Admin UI jumps to left and right when new blade is opened

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-community#242]
When switching from one product blade to another in the product list UI jumps scrolls left and then right creating a jumping affect.

To reproduce, go to catalog product list and make sure browser window can't fit all 3 blades (catalog list, product list and product detail). Now click next product in the list, you should see UI jumping when existing product blade is closed and after the new blade is opened.

**Comment by eMazeika** [comment]
this is a side effect of our animation, but it's "by design".

**Comment by Woland2k** [comment]
need to change it
