### ISSUE TITLE
The thread <no name> has exited with code 0 (0x0)

### ISSUE THREAD

**Issue by luciano-jr** [VirtoCommerce/vc-community#244]
I have been tried start the VirtoCommerce2 project like Getting Started guide recommend but I can't because I have "The thread <no name> has exited with code 0 (0x0)" error ever.

I hope that I config the SQL Server correctly but when I debug the "Startup.cs" file on VirtoCommerce.Platform.Web the application stop on line 98 when it is called "InitializePlatform" method.

**Comment by tatarincev** [comment]
Hi @luciano-jr, can you show connection string in VCF manager web.config?

**Comment by luciano-jr** [comment]
Sure, follow bellow:

<add name="VirtoCommerce" connectionString="Data Source=(local);Initial Catalog=VirtoCommerce2;Persist Security Info=True;User ID=virto;Password=virto;MultipleActiveResultSets=True;Connect Timeout=420" providerName="System.Data.SqlClient" />

**Comment by tatarincev** [comment]
Very similar to the problems with the connection to the database. But connection string looks correct. Can you manually connect to DB with these credentials?

**Comment by luciano-jr** [comment]
I can connect manually with user and password virto

**Comment by eMazeika** [comment]
Is similar issue the key point was "Data Source=(local)" and SQL Express named instance running. Are you sure you can connect to default instance?
Are there any errors in DB logs?

**Comment by tatarincev** [comment]
If you use SQL express you should use some like this 
connectionString="Data Source=MC103\SQLEXPRESS;Initial Catalog=VirtoCommerce2.7;Persist Security Info=True;User ID=virto;Password=virto;MultipleActiveResultSets=True;Connect Timeout=420"

**Comment by luciano-jr** [comment]
I am use SQL express and I changed my string connection like @tatarincev proposed and I got the same error.

Both VS and SQL Managment Studio I can connect on instance using virto user

**Comment by tatarincev** [comment]
Are you sure what thread freezes on 98 line, maybe different line inside InitializePlatform method?

**Comment by luciano-jr** [comment]
Actually I have been changed something in my SQL instance and then I have normal connection and the migrations are executing. 

This proccess still running right now but I can see some tables on database.

I am sorry guys but I do not know what is exactly I changed to fix the connection

**Comment by tatarincev** [comment]
As I right understand problem was solved?

**Comment by luciano-jr** [comment]
Yes, thank you for your time
