### ISSUE TITLE
Rejected User(Manager/Customer) is not rejected when logging in

### ISSUE THREAD

**Issue by jvdonk** [VirtoCommerce/vc-community#245]
I added a new user of Account type "Manager" which set the State on Approved. When I reject this user, either directly after creating or after the user has logged in successfully at least once, this user is still able to login to the admin.

It throws 401 errors when viewing notifications and user or notification settings, but I think the user shouldn't be able to login in the first place?

Looking at the code there is no check on Account state in the api/platform/security/login API which causes this effect.

**Comment by tatarincev** [comment]
Thanks @jvdonk, its ordinary bug. We definitely will fix it as soon as possible.

**Comment by jvdonk** [comment]
I think it's related to #245, as in that AccountState properties aren't checked as you just explaned in #245. Right?

**Comment by tatarincev** [comment]
Yes you right, I already fix this issue. Accept/Reject and login for Customer account will works as  expected.
