### ISSUE TITLE
Please clarify release management

### ISSUE THREAD

**Issue by jvdonk** [VirtoCommerce/vc-community#249]
Versions are re-released, is that right? By it looks like build-versions: 2.6.1102 / 2.6.1173?

Is it because of release overhead? Maybe use sub-version release: 2.6.1, 2.6.2 etc?

I wanted to check what is changed(committed) after when I downloaded the 2.6 source(december 2015) and stumbled upon a different 2.6 release(12 days ago). Now I don't know up to which commit I downloaded. :)

**Comment by tatarincev** [comment]
Hi @jvdonk, such a situation will not happen again next all releases will be without overhead same version number. Its was unique-terrible release :)

**Comment by jvdonk** [comment]
Ok, great. Tnx!
