### ISSUE TITLE
ESWorker Role doesn't work

### ISSUE THREAD

**Issue by kodermax** [VirtoCommerce/vc-community#25]
Установил на azure движок, но почему то роль elasticsearch не работае http://motul-search.cloudapp.net:9200 не отвечает на этот порт, как быть?

**Comment by Woland2k** [comment]
Are there any errors in azure role? Can you check the status of it?

**Comment by kodermax** [comment]
Only these 
![err4](https://cloud.githubusercontent.com/assets/590985/5905533/cb991530-a5a1-11e4-93ff-3c6694f70aab.png)

**Comment by Woland2k** [comment]
You can change the log settings for the service to get more information. But speaking of service, what is the status of it, does it say "Running" on azure website itself?

**Comment by kodermax** [comment]
Yes it's running. How can y reinstall this role on azure?

**Comment by kodermax** [comment]
New errors.
![err5](https://cloud.githubusercontent.com/assets/590985/5905933/e2c6193a-a5a4-11e4-9936-2b440e6489d5.png)

**Comment by Woland2k** [comment]
Try expanding application logs. Simply click on them and select view all. Which version of VC are you running? 1.12?

**Comment by kodermax** [comment]
also erros

RoleInstanceId: ESWorkerRole_IN_0; DeploymentId: 37cef048b7ac4475ae901198d99fef67; RoleName: ESWorkerRole
Checking VM Type
File HandlerEnvironment.json not found. Extension set to PAAS
Store Size: 8192
Reading XML configuration file
Will use thumbprint 78AD2563BA50E49635B796D5454C965F143F1626
Decrypting private configuration
Thumbprint: 78AD2563BA50E49635B796D5454C965F143F1626
Stopping the running plugin, if any
No DiagnosticsPlugin is running.
Killing any DiagnosticsPlugin that might remain.
Killing any MonAgentHost that might remain.
Diagnostics plugin stopped successfully
Resetting DiagnosticPlugin
Starting DiagnosticPlugin.exe DiagnosticPlugin-ShutdownEvent DiagnosticPlugin-TotalShutdownEvent -wadVer1v3
Starting DiagnosticsPlugin
Checking VM Type
File HandlerEnvironment.json not found. Extension set to PAAS
RcfFileName: C:\Config\37cef048b7ac4475ae901198d99fef67.37cef048b7ac4475ae901198d99fef67.ESWorkerRole_IN_0.2.xml
RoleInstanceId: ESWorkerRole_IN_0; DeploymentId: 37cef048b7ac4475ae901198d99fef67; RoleName: ESWorkerRole
Checking VM Type
File HandlerEnvironment.json not found. Extension set to PAAS
Store Size: 8192
Reading XML configuration file
Will use thumbprint 78AD2563BA50E49635B796D5454C965F143F1626
Decrypting private configuration
Thumbprint: 78AD2563BA50E49635B796D5454C965F143F1626
WadCfg is provided in initial configuration. Using that to initialize Diagnostics.
<PublicConfig xmlns="http://schemas.microsoft.com/ServiceHosting/2010/10/DiagnosticsConfiguration">  <WadCfg>    <DiagnosticMonitorConfiguration overallQuotaInMB="4096">      <DiagnosticInfrastructureLogs scheduledTransferLogLevelFilter="Error" />      <Directories scheduledTransferPeriod="PT1M">        <IISLogs containerName="wad-iis-logfiles" />        <FailedRequestLogs containerName="wad-failedrequestlogs" />      </Directories>      <PerformanceCounters scheduledTransferPeriod="PT1M">        <PerformanceCounterConfiguration counterSpecifier="\Memory\Available MBytes" sampleRate="PT3M" />        <PerformanceCounterConfiguration counterSpecifier="\Web Service(_Total)\ISAPI Extension Requests/sec" sampleRate="PT3M" />        <PerformanceCounterConfiguration counterSpecifier="\Web Service(_Total)\Bytes Total/Sec" sampleRate="PT3M" />        <PerformanceCounterConfiguration counterSpecifier="\ASP.NET Applications(__Total__)\Requests/Sec" sampleRate="PT3M" />        <PerformanceCounterConfiguration counterSpecifier="\ASP.NET Applications(__Total__)\Errors Total/Sec" sampleRate="PT3M" />        <PerformanceCounterConfiguration counterSpecifier="\ASP.NET\Requests Queued" sampleRate="PT3M" />        <PerformanceCounterConfiguration counterSpecifier="\ASP.NET\Requests Rejected" sampleRate="PT3M" />        <PerformanceCounterConfiguration counterSpecifier="\Processor(_Total)\% Processor Time" sampleRate="PT3M" />      </PerformanceCounters>      <WindowsEventLog scheduledTransferPeriod="PT1M">        <DataSource name="Application!*" />      </WindowsEventLog>      <CrashDumps>        <CrashDumpConfiguration processName="WaIISHost.exe" />        <CrashDumpConfiguration processName="WaWorkerHost.exe" />        <CrashDumpConfiguration processName="w3wp.exe" />      </CrashDumps>      <Logs scheduledTransferPeriod="PT1M" scheduledTransferLogLevelFilter="Error" />    </DiagnosticMonitorConfiguration>  </WadCfg>  <StorageAccount>motul</StorageAccount></PublicConfig>
Private setting is loaded
Successfully created checkpoint file C:\Resources\{36789130-115f-bc41-b83f-2cc45ae5b784}\directory\37cef048b7ac4475ae901198d99fef67.ESWorkerRole.DiagnosticStore\WAD0103\Configuration\Checkpoint.txt
Will use local resource directory C:\Resources\{36789130-115f-bc41-b83f-2cc45ae5b784}\directory\37cef048b7ac4475ae901198d99fef67.ESWorkerRole.DiagnosticStore\WAD0103
Will use endpoint https://core.windows.net/ for storage.
Expanding path %SystemDrive%\inetpub\logs\LogFiles to D:\inetpub\logs\LogFiles
Expanding path %SystemDrive%\inetpub\logs\FailedReqLogFiles to D:\inetpub\logs\FailedReqLogFiles
Created IIS log watch item: "D:\inetpub\logs\LogFiles"
Created IIS failed requests watch item: "D:\inetpub\logs\FailedReqLogFiles"
MonAgentHost.exe started
DiagnoticsPlugin started.
DiagnoticsPlugin now waiting on events "DiagnosticPlugin-ShutdownEvent" or "DiagnosticPlugin-TotalShutdownEvent".
DiagnosticsPlugin launched successfully with new configuration
DiagnosticPlugin exited with code 0
Checking VM Type
File HandlerEnvironment.json not found. Extension set to PAAS
RcfFileName: C:\Config\37cef048b7ac4475ae901198d99fef67.37cef048b7ac4475ae901198d99fef67.ESWorkerRole_IN_0.3.xml
RoleInstanceId: ESWorkerRole_IN_0; DeploymentId: 37cef048b7ac4475ae901198d99fef67; RoleName: ESWorkerRole
Checking VM Type
File HandlerEnvironment.json not found. Extension set to PAAS
Store Size: 8192
Reading XML configuration file
Will use thumbprint EB33A81F0F0DCCC08E5098075AD642840F4ADCE8
Decrypting private configuration
No certficate with given thumbprint found in the certificate store. Thumbprint:EB33A81F0F0DCCC08E5098075AD642840F4ADCE8
Retrying after 30 seconds. Retry attempt 1
Thumbprint: EB33A81F0F0DCCC08E5098075AD642840F4ADCE8
Stopping the running plugin, if any
Found a MonAgentHost.exe. WadArguments: "D:\Packages\Plugins\Microsoft.Azure.Diagnostics.PaaSDiagnostics\1.3.1.6\Monitor\x64\MonAgentHost.exe" -LocalPath "C:\Resources\{36789130-115f-bc41-b83f-2cc45ae5b784}\directory\37cef048b7ac4475ae901198d99fef67.ESWorkerRole.DiagnosticStore\WAD0103"  -ConfigFile "C:\Resources\{36789130-115f-bc41-b83f-2cc45ae5b784}\directory\37cef048b7ac4475ae901198d99fef67.ESWorkerRole.DiagnosticStore\WAD0103\Configuration\MaConfig.xml" -ShutDownEvent WADDM-ShutDown-bce63ce75d2542f3bf4068527406f509  -TotalShutDownEvent WADDM-TotalShutDown-bce63ce75d2542f3bf4068527406f509 -InitializedEvent WADM-StartUp-bce63ce75d2542f3bf4068527406f509 -parent 3044 -events -wadVer1v3 -UseProxyServer.
Found a DiagnosticsPlugin.exe. WadArguments: "D:\Packages\Plugins\Microsoft.Azure.Diagnostics.PaaSDiagnostics\1.3.1.6\DiagnosticsPlugin.exe" DiagnosticPlugin-ShutdownEvent DiagnosticPlugin-TotalShutdownEvent -wadVer1v3.
Reading XML configuration file
Will use thumbprint EB33A81F0F0DCCC08E5098075AD642840F4ADCE8
Decrypting private configuration
Thumbprint: EB33A81F0F0DCCC08E5098075AD642840F4ADCE8
Shutdown event signaled.
Application: DiagnosticsAgent.exeFramework Version: v4.0.30319Description: The process was terminated due to an unhandled exception.Exception Info: System.ArgumentExceptionStack:   at Microsoft.WindowsAzure.Plugins.Diagnostics.DiagnosticsAgentManager.<StartAgent>b__0()   at Microsoft.WindowsAzure.Plugins.Common.BlockingExecutionEnvironment.Execute(System.Func`1<Int32>)   at Microsoft.WindowsAzure.Plugins.Diagnostics.Program.Main(System.String[])
Faulting application name: DiagnosticsAgent.exe, version: 2.4.6489.4, time stamp: 0x5407b51aFaulting module name: KERNELBASE.dll, version: 6.3.9600.17415, time stamp: 0x54505737Exception code: 0xe0434352Fault offset: 0x0000000000008b9cFaulting process id: 0x3a4Faulting application start time: 0x01d03995d7cbb8eaFaulting application path: E:\plugins\Diagnostics\DiagnosticsAgent.exeFaulting module path: D:\Windows\system32\KERNELBASE.dllReport Id: 17498c3a-a589-11e4-80bd-00155dd0f9eaFaulting package full name: Faulting package-relative application ID: 
Exiting Diagnostics.
Found a running wad2 MA sharing the same local directory.
DiagnosticPlugin.exe exit with code 0
Killing any DiagnosticsPlugin that might remain.
Found a DiagnosticsPlugin.exe. WadArguments: "D:\Packages\Plugins\Microsoft.Azure.Diagnostics.PaaSDiagnostics\1.3.1.6\DiagnosticsPlugin.exe" DiagnosticPlugin-ShutdownEvent DiagnosticPlugin-TotalShutdownEvent -wadVer1v3.
Killing any MonAgentHost that might remain.
Diagnostics plugin stopped successfully
Resetting DiagnosticPlugin
Starting DiagnosticPlugin.exe DiagnosticPlugin-ShutdownEvent DiagnosticPlugin-TotalShutdownEvent -wadVer1v3
Starting DiagnosticsPlugin
Checking VM Type
File HandlerEnvironment.json not found. Extension set to PAAS
RcfFileName: C:\Config\37cef048b7ac4475ae901198d99fef67.37cef048b7ac4475ae901198d99fef67.ESWorkerRole_IN_0.3.xml
RoleInstanceId: ESWorkerRole_IN_0; DeploymentId: 37cef048b7ac4475ae901198d99fef67; RoleName: ESWorkerRole
Checking VM Type
File HandlerEnvironment.json not found. Extension set to PAAS
Store Size: 8192
Reading XML configuration file
Will use thumbprint EB33A81F0F0DCCC08E5098075AD642840F4ADCE8
Decrypting private configuration
Thumbprint: EB33A81F0F0DCCC08E5098075AD642840F4ADCE8
WadCfg is provided in initial configuration. Using that to initialize Diagnostics.
<PublicConfig xmlns="http://schemas.microsoft.com/ServiceHosting/2010/10/DiagnosticsConfiguration">  <WadCfg>    <DiagnosticMonitorConfiguration overallQuotaInMB="4096">      <DiagnosticInfrastructureLogs scheduledTransferLogLevelFilter="Error" />      <Directories scheduledTransferPeriod="PT1M">        <IISLogs containerName="wad-iis-logfiles" />        <FailedRequestLogs containerName="wad-failedrequestlogs" />      </Directories>      <PerformanceCounters scheduledTransferPeriod="PT1M">        <PerformanceCounterConfiguration counterSpecifier="\Memory\Available MBytes" sampleRate="PT3M" />        <PerformanceCounterConfiguration counterSpecifier="\Web Service(_Total)\ISAPI Extension Requests/sec" sampleRate="PT3M" />        <PerformanceCounterConfiguration counterSpecifier="\Web Service(_Total)\Bytes Total/Sec" sampleRate="PT3M" />        <PerformanceCounterConfiguration counterSpecifier="\ASP.NET Applications(__Total__)\Requests/Sec" sampleRate="PT3M" />        <PerformanceCounterConfiguration counterSpecifier="\ASP.NET Applications(__Total__)\Errors Total/Sec" sampleRate="PT3M" />        <PerformanceCounterConfiguration counterSpecifier="\ASP.NET\Requests Queued" sampleRate="PT3M" />        <PerformanceCounterConfiguration counterSpecifier="\ASP.NET\Requests Rejected" sampleRate="PT3M" />        <PerformanceCounterConfiguration counterSpecifier="\Processor(_Total)\% Processor Time" sampleRate="PT3M" />      </PerformanceCounters>      <WindowsEventLog scheduledTransferPeriod="PT1M">        <DataSource name="Application!*" />      </WindowsEventLog>      <CrashDumps>        <CrashDumpConfiguration processName="WaIISHost.exe" />        <CrashDumpConfiguration processName="WaWorkerHost.exe" />        <CrashDumpConfiguration processName="w3wp.exe" />      </CrashDumps>      <Logs scheduledTransferPeriod="PT1M" scheduledTransferLogLevelFilter="Error" />    </DiagnosticMonitorConfiguration>  </WadCfg>  <StorageAccount>motul</StorageAccount></PublicConfig>
Private setting is loaded
Checkpoint file is presentC:\Resources\{36789130-115f-bc41-b83f-2cc45ae5b784}\directory\37cef048b7ac4475ae901198d99fef67.ESWorkerRole.DiagnosticStore\WAD0103\Configuration\Checkpoint.txt
Will use local resource directory C:\Resources\{36789130-115f-bc41-b83f-2cc45ae5b784}\directory\37cef048b7ac4475ae901198d99fef67.ESWorkerRole.DiagnosticStore\WAD0103
Will use endpoint https://core.windows.net/ for storage.
Expanding path %SystemDrive%\inetpub\logs\LogFiles to D:\inetpub\logs\LogFiles
Expanding path %SystemDrive%\inetpub\logs\FailedReqLogFiles to D:\inetpub\logs\FailedReqLogFiles
Created IIS log watch item: "D:\inetpub\logs\LogFiles"
Created IIS failed requests watch item: "D:\inetpub\logs\FailedReqLogFiles"
MonAgentHost.exe started
DiagnoticsPlugin started.
DiagnoticsPlugin now waiting on events "DiagnosticPlugin-ShutdownEvent" or "DiagnosticPlugin-TotalShutdownEvent".
DiagnosticsPlugin launched successfully with new configuration
DiagnosticPlugin exited with code 0
Performance counters for the WmiApRpl (WmiApRpl) service were removed successfully. The Record Data contains the new values of the system Last Counter and Last Help registry entries.
Performance counters for the WmiApRpl (WmiApRpl) service were loaded successfully. The Record Data in the data section contains the new index values assigned to this service.
The VSS service is shutting down due to shutdown event from the Service Control Manager. 


The User Profile Service has stopped.  
The EventSystem sub system is suppressing duplicate event log entries for a duration of 86400 seconds.  The suppression timeout can be controlled by a REG_DWORD value named SuppressDuplicateDuration under the following registry key: HKLM\Software\Microsoft\EventSystem\EventLog.
The User Profile Service has started successfully.  
Communication port '\QuotaCommPort' to the 'Quota' filter driver was established.

Windows Management Instrumentation Service started sucessfully
Windows Management Instrumentation Service subsystems initialized successfully
Service started successfully.
Checking VM Type
Application: DiagnosticsAgent.exeFramework Version: v4.0.30319Description: The process was terminated due to an unhandled exception.Exception Info: System.ArgumentExceptionStack:   at Microsoft.WindowsAzure.Plugins.Diagnostics.DiagnosticsAgentManager.<StartAgent>b__0()   at Microsoft.WindowsAzure.Plugins.Common.BlockingExecutionEnvironment.Execute(System.Func`1<Int32>)   at Microsoft.WindowsAzure.Plugins.Diagnostics.Program.Main(System.String[])
File HandlerEnvironment.json not found. Extension set to PAAS
RcfFileName: C:\Config\37cef048b7ac4475ae901198d99fef67.37cef048b7ac4475ae901198d99fef67.ESWorkerRole_IN_0.1.xml
RoleInstanceId: ESWorkerRole_IN_0; DeploymentId: 37cef048b7ac4475ae901198d99fef67; RoleName: ESWorkerRole
Checking VM Type
File HandlerEnvironment.json not found. Extension set to PAAS
Store Size: 8192
Reading XML configuration file
Will use thumbprint EB33A81F0F0DCCC08E5098075AD642840F4ADCE8
Faulting application name: DiagnosticsAgent.exe, version: 2.4.6489.4, time stamp: 0x5407b51aFaulting module name: KERNELBASE.dll, version: 6.3.9600.17415, time stamp: 0x54505737Exception code: 0xe0434352Fault offset: 0x0000000000008b9cFaulting process id: 0x948Faulting application start time: 0x01d03997ed6c8662Faulting application path: E:\plugins\Diagnostics\DiagnosticsAgent.exeFaulting module path: D:\Windows\system32\KERNELBASE.dllReport Id: 2d0431e8-a58b-11e4-80be-00155dd0f9eaFaulting package full name: Faulting package-relative application ID: 
Decrypting private configuration
Thumbprint: EB33A81F0F0DCCC08E5098075AD642840F4ADCE8
Stopping the running plugin, if any
No DiagnosticsPlugin is running.
Killing any DiagnosticsPlugin that might remain.
Killing any MonAgentHost that might remain.
Diagnostics plugin stopped successfully
Resetting DiagnosticPlugin
Starting DiagnosticPlugin.exe DiagnosticPlugin-ShutdownEvent DiagnosticPlugin-TotalShutdownEvent -wadVer1v3
Starting DiagnosticsPlugin
Checking VM Type
File HandlerEnvironment.json not found. Extension set to PAAS
RcfFileName: C:\Config\37cef048b7ac4475ae901198d99fef67.37cef048b7ac4475ae901198d99fef67.ESWorkerRole_IN_0.1.xml
RoleInstanceId: ESWorkerRole_IN_0; DeploymentId: 37cef048b7ac4475ae901198d99fef67; RoleName: ESWorkerRole
Checking VM Type
File HandlerEnvironment.json not found. Extension set to PAAS
Store Size: 8192
Reading XML configuration file
Will use thumbprint EB33A81F0F0DCCC08E5098075AD642840F4ADCE8
Decrypting private configuration
Thumbprint: EB33A81F0F0DCCC08E5098075AD642840F4ADCE8
WadCfg is provided in initial configuration. Using that to initialize Diagnostics.
<PublicConfig xmlns="http://schemas.microsoft.com/ServiceHosting/2010/10/DiagnosticsConfiguration">  <WadCfg>    <DiagnosticMonitorConfiguration overallQuotaInMB="4096">      <DiagnosticInfrastructureLogs scheduledTransferLogLevelFilter="Error" />      <Directories scheduledTransferPeriod="PT1M">        <IISLogs containerName="wad-iis-logfiles" />        <FailedRequestLogs containerName="wad-failedrequestlogs" />      </Directories>      <PerformanceCounters scheduledTransferPeriod="PT1M">        <PerformanceCounterConfiguration counterSpecifier="\Memory\Available MBytes" sampleRate="PT3M" />        <PerformanceCounterConfiguration counterSpecifier="\Web Service(_Total)\ISAPI Extension Requests/sec" sampleRate="PT3M" />        <PerformanceCounterConfiguration counterSpecifier="\Web Service(_Total)\Bytes Total/Sec" sampleRate="PT3M" />        <PerformanceCounterConfiguration counterSpecifier="\ASP.NET Applications(__Total__)\Requests/Sec" sampleRate="PT3M" />        <PerformanceCounterConfiguration counterSpecifier="\ASP.NET Applications(__Total__)\Errors Total/Sec" sampleRate="PT3M" />        <PerformanceCounterConfiguration counterSpecifier="\ASP.NET\Requests Queued" sampleRate="PT3M" />        <PerformanceCounterConfiguration counterSpecifier="\ASP.NET\Requests Rejected" sampleRate="PT3M" />        <PerformanceCounterConfiguration counterSpecifier="\Processor(_Total)\% Processor Time" sampleRate="PT3M" />      </PerformanceCounters>      <WindowsEventLog scheduledTransferPeriod="PT1M">        <DataSource name="Application!*" />      </WindowsEventLog>      <CrashDumps>        <CrashDumpConfiguration processName="WaIISHost.exe" />        <CrashDumpConfiguration processName="WaWorkerHost.exe" />        <CrashDumpConfiguration processName="w3wp.exe" />      </CrashDumps>      <Logs scheduledTransferPeriod="PT1M" scheduledTransferLogLevelFilter="Error" />    </DiagnosticMonitorConfiguration>  </WadCfg>  <StorageAccount>motul</StorageAccount></PublicConfig>
Private setting is loaded
Checkpoint file is presentC:\Resources\{36789130-115f-bc41-b83f-2cc45ae5b784}\directory\37cef048b7ac4475ae901198d99fef67.ESWorkerRole.DiagnosticStore\WAD0103\Configuration\Checkpoint.txt
Will use local resource directory C:\Resources\{36789130-115f-bc41-b83f-2cc45ae5b784}\directory\37cef048b7ac4475ae901198d99fef67.ESWorkerRole.DiagnosticStore\WAD0103
Will use endpoint https://core.windows.net/ for storage.
Expanding path %SystemDrive%\inetpub\logs\LogFiles to D:\inetpub\logs\LogFiles
Expanding path %SystemDrive%\inetpub\logs\FailedReqLogFiles to D:\inetpub\logs\FailedReqLogFiles
Created IIS log watch item: "D:\inetpub\logs\LogFiles"
Created IIS failed requests watch item: "D:\inetpub\logs\FailedReqLogFiles"
MSDTC started with the following settings: Security Configuration (OFF = 0 and ON = 1): Allow Remote Administrator = 0, Network Clients = 0, Transaction Manager Communication:  Allow Inbound Transactions = 0, Allow Outbound Transactions = 0, Transaction Internet Protocol (TIP) = 0,  Enable XA Transactions = 0,  Enable SNA LU 6.2 Transactions = 1,  MSDTC Communications Security = Mutual Authentication Required, Account = NT AUTHORITY\NetworkService,  Firewall Exclusion Detected = 0 Transaction Bridge Installed = 0 Filtering Duplicate Events = 1
The Software Protection service is starting.Parameters:<none>
MonAgentHost.exe started
DiagnoticsPlugin started.
DiagnoticsPlugin now waiting on events "DiagnosticPlugin-ShutdownEvent" or "DiagnosticPlugin-TotalShutdownEvent".
Initialization status for service objects.D:\Windows\system32\sppwinob.dll, msft:spp/windowsfunctionality/agent/7.0, 0x00000000, 0x00000000D:\Windows\system32\sppobjs.dll, msft:rm/algorithm/inherited/1.0, 0x00000000, 0x00000000D:\Windows\system32\sppobjs.dll, msft:rm/algorithm/phone/1.0, 0x00000000, 0x00000000D:\Windows\system32\sppobjs.dll, msft:rm/algorithm/pkey/detect, 0x00000000, 0x00000000D:\Windows\system32\sppobjs.dll, msft:spp/ActionScheduler/1.0, 0x00000000, 0x00000000D:\Windows\system32\sppobjs.dll, msft:spp/TaskScheduler/1.0, 0x00000000, 0x00000000D:\Windows\system32\sppobjs.dll, msft:spp/statecollector/pkey, 0x00000000, 0x00000000D:\Windows\system32\sppobjs.dll, msft:spp/volume/services/kms/1.0, 0x00000000, 0x00000000D:\Windows\system32\sppobjs.dll, msft:spp/volume/services/kms/activationinfo/1.0, 0x00000000, 0x00000000
DiagnosticsPlugin launched successfully with new configuration
DiagnosticPlugin exited with code 0
Duplicate definition of policy found. Policy name=Security-SPP-WriteWauMarker  Priority=500
These policies are being excluded since they are only defined with override-only attribute.Policy Names=(DFSN-ServerService-StandaloneRootLimit) (FailoverCluster-ClusWMI-IsClusterEnabled) (MathRecognizerEventsLicensing-EnableMathRecognizer) (Microsoft-Windows-CertificateServices-CA-AdvancedTemplateSupport) (Microsoft-Windows-CertificateServices-CA-CertificateManagerRestrictionSupport) (Microsoft-Windows-CertificateServices-CA-CrossForestEnrollmentSupport) (Microsoft-Windows-CertificateServices-CA-ExitModuleSMTPSupport) (Microsoft-Windows-CertificateServices-CA-RoleSeparationSupport) (Microsoft-Windows-Fax-Common-DeviceLimit) (Microsoft-Windows-Fax-Common-EnableServerPolicy) (Microsoft-Windows-OfflineFiles-Core-BranchCachingEnabled) (Microsoft-Windows-OfflineFiles-Core-FeatureEnabled) (Microsoft-Windows-SensorsLicense-EnableCPL) (Microsoft.Windows.Smc-Enabled) (PeerToPeerBase-IdManager-EnabledPolicy) (PeerToPeerBase-Pnrp-EnabledPolicy) (Personalization-Enabled) (Printing-Spooler-Pmc-Licensing-Enabled) (SecureStartupFeature-Enabled) (SecureStartupFeature-Enabled-Driver) (SecureStartupFeature-Enabled-Premium) (SecureStartupFeature-PerfWarning) (Security-SPP-Reserved-EnableNotificationMode) (SnippingToolLicensing-Enabled) (TSProxy-EdgeAdapter-MaxConnections) (TabletPC-MathInputLicensing-EnableMathInput) (TabletPCCoreInkRecognitionLicensing-EnableText) (TabletPCInputPanel-EnableTIP) (TabletPCInputPanel-EnableTIPSynced) (TabletPCInputPersonalization-EnablePersonalization) (TabletPCPlatformInput-core-MultiTouchGestures) (TabletPCPlatformInput-core-SFP) (Telnet-Server-EnableTelnetServer) (TiffIFilterLicensing-EnableTiffIFilter) (WMPPlayer-HMEAllowed) (WinStoreUI-Enabled) (microsoft-windows-virtualization-licensing-EnableHyperVReplica) (nfs-admincmdtools-enabled) (nfs-clientcmdtools-enabled) (nfs-clientcore-enabled) (nfs-servercmdtools-enabled) (nfs-servercore-enabled) (psync-Enabled) (snis-Enabled) App Id=55c92734-d682-4d71-983e-d6ec3f16059fSku Id=640e7014-6f45-4106-bd1d-ac17a812a2d1
The Software Protection service has completed licensing status check.Application Id=55c92734-d682-4d71-983e-d6ec3f16059fLicensing Status=1: 00091344-1ea4-4f37-b789-01750ba6988c, 1, 0 [(0 [0xC004F014, 0, 0], [(?)(?)(?)(?)(?)(?)(?)(?)])(1 )(2 )]2: 1226e046-263d-414c-824f-0d4f458cee3a, 1, 0 [(0 [0xC004F014, 0, 0], [(?)(?)(?)(?)(?)(?)(?)(?)])(1 )(2 )]3: 1cc95b8e-1b6e-42cc-9768-9e84ce28cc3f, 1, 0 [(0 [0xC004F014, 0, 0], [(?)(?)(?)(?)(?)(?)(?)(?)])(1 )(2 )]4: 640e7014-6f45-4106-bd1d-ac17a812a2d1, 1, 0 [(0 [0x00000000, 1, 0], [(?)( 1 0x00000000)(?)( 2 0x00000000 0 0 msft:rm/algorithm/inherited/1.0 0x00000000 8686)(?)(?)( 10 0x00000000 msft:rm/algorithm/flags/1.0)(?)])(1 )(2 )]5: 641f81b2-63c2-47dd-aba7-c24bf651ff85, 1, 0 [(0 [0xC004F014, 0, 0], [(?)(?)(?)(?)(?)(?)(?)(?)])(1 )(2 )]6: 66d129b6-eae9-414e-a39a-ea5b8be961cc, 1, 0 [(0 [0xC004F014, 0, 0], [(?)(?)(?)(?)(?)(?)(?)(?)])(1 )(2 )]7: acf1b4fd-1c55-4f2d-a60b-415ac958ad88, 1, 0 [(0 [0xC004F014, 0, 0], [(?)(?)(?)(?)(?)(?)(?)(?)])(1 )(2 )]8: c2d61e88-5598-4e77-aae2-286dc6670a89, 1, 0 [(0 [0xC004F014, 0, 0], [(?)(?)(?)(?)(?)(?)(?)(?)])(1 )(2 )]9: dcb88f6f-b090-405b-850e-dabcccf3693f, 1, 0 [(0 [0xC004F014, 0, 0], [(?)(?)(?)(?)(?)(?)(?)(?)])(1 )(2 )]10: fecbc8f2-a4b1-402a-92e7-5d81a6fe3e80, 1, 0 [(0 [0xC004F014, 0, 0], [(?)(?)(?)(?)(?)(?)(?)(?)])(1 )(2 )]11: 9d0bb49b-21a1-4354-9981-ec5dd9393961, 1, 0 [(0 [0xC004F014, 0, 0], [(?)(?)(?)(?)(?)(?)(?)(?)])(1 )(2 )]
The Software Protection service has started.6.3.9600.16497
Performance counters for the WmiApRpl (WmiApRpl) service were removed successfully. The Record Data contains the new values of the system Last Counter and Last Help registry entries.
Performance counters for the WmiApRpl (WmiApRpl) service were loaded successfully. The Record Data in the data section contains the new index values assigned to this service.
Successfully scheduled Software Protection service for re-start at 2015-02-01T19:28:56Z. Reason: RulesEngine.
The Software Protection service has stopped.
Performance counters for the WmiApRpl (WmiApRpl) service were removed successfully. The Record Data contains the new values of the system Last Counter and Last Help registry entries.
Performance counters for the WmiApRpl (WmiApRpl) service were loaded successfully. The Record Data in the data section contains the new index values assigned to this service.
Checking VM Type
File HandlerEnvironment.json not found. Extension set to PAAS
RcfFileName: C:\Config\37cef048b7ac4475ae901198d99fef67.37cef048b7ac4475ae901198d99fef67.ESWorkerRole_IN_0.2.xml
RoleInstanceId: ESWorkerRole_IN_0; DeploymentId: 37cef048b7ac4475ae901198d99fef67; RoleName: ESWorkerRole
Checking VM Type
File HandlerEnvironment.json not found. Extension set to PAAS
Store Size: 8192
Reading XML configuration file
Will use thumbprint B55CF6FBAA01D23990A67DEB3FFBB0705EFA813A
Decrypting private configuration
No certficate with given thumbprint found in the certificate store. Thumbprint:B55CF6FBAA01D23990A67DEB3FFBB0705EFA813A
Retrying after 30 seconds. Retry attempt 1
Application: DiagnosticsAgent.exeFramework Version: v4.0.30319Description: The process was terminated due to an unhandled exception.Exception Info: System.ArgumentExceptionStack:   at Microsoft.WindowsAzure.Plugins.Diagnostics.DiagnosticsAgentManager.<StartAgent>b__0()   at Microsoft.WindowsAzure.Plugins.Common.BlockingExecutionEnvironment.Execute(System.Func`1<Int32>)   at Microsoft.WindowsAzure.Plugins.Diagnostics.Program.Main(System.String[])
Faulting application name: DiagnosticsAgent.exe, version: 2.4.6489.4, time stamp: 0x5407b51aFaulting module name: KERNELBASE.dll, version: 6.3.9600.17415, time stamp: 0x54505737Exception code: 0xe0434352Fault offset: 0x0000000000008b9cFaulting process id: 0x6c0Faulting application start time: 0x01d03998cbf2724fFaulting application path: E:\plugins\Diagnostics\DiagnosticsAgent.exeFaulting module path: D:\Windows\system32\KERNELBASE.dllReport Id: 0b580e04-a58c-11e4-80be-00155dd0f9eaFaulting package full name: Faulting package-relative application ID: 
Thumbprint: B55CF6FBAA01D23990A67DEB3FFBB0705EFA813A
Stopping the running plugin, if any
Found a MonAgentHost.exe. WadArguments: "D:\Packages\Plugins\Microsoft.Azure.Diagnostics.PaaSDiagnostics\1.3.1.6\Monitor\x64\MonAgentHost.exe" -LocalPath "C:\Resources\{36789130-115f-bc41-b83f-2cc45ae5b784}\directory\37cef048b7ac4475ae901198d99fef67.ESWorkerRole.DiagnosticStore\WAD0103"  -ConfigFile "C:\Resources\{36789130-115f-bc41-b83f-2cc45ae5b784}\directory\37cef048b7ac4475ae901198d99fef67.ESWorkerRole.DiagnosticStore\WAD0103\Configuration\MaConfig.xml" -ShutDownEvent WADDM-ShutDown-f91dfdbf27de4e62bcceb31e521f7be5  -TotalShutDownEvent WADDM-TotalShutDown-f91dfdbf27de4e62bcceb31e521f7be5 -InitializedEvent WADM-StartUp-f91dfdbf27de4e62bcceb31e521f7be5 -parent 2924 -events -wadVer1v3 -UseProxyServer.
Found a DiagnosticsPlugin.exe. WadArguments: "D:\Packages\Plugins\Microsoft.Azure.Diagnostics.PaaSDiagnostics\1.3.1.6\DiagnosticsPlugin.exe" DiagnosticPlugin-ShutdownEvent DiagnosticPlugin-TotalShutdownEvent -wadVer1v3.
Reading XML configuration file
Will use thumbprint B55CF6FBAA01D23990A67DEB3FFBB0705EFA813A
Decrypting private configuration
Thumbprint: B55CF6FBAA01D23990A67DEB3FFBB0705EFA813A
Shutdown event signaled.
File Server Resource Manager was unable to access the following file or volume: 'B:'.  This file or volume might be locked by another application right now, or you might need to give Local System access to it.

**Comment by kodermax** [comment]
i have latest clone this repository

**Comment by Woland2k** [comment]
Is this application logs or infrastructure logs? Need application logs as they would be more descriptive. You can also try deleting the container called ESWorkerRole-0 in storage and restart the ES service. Sometimes you might have an older version of indexes saved that will not work with an update ES version.

**Comment by kodermax** [comment]
I can install wirhout error using VC 1.12.
But i installed cloud service for www. What is better cloud service or website?

**Comment by Woland2k** [comment]
It is typically easier to run as a website, 1.13 version now includes powershell scripts that setup site as a website while 1.12 set it up as a cloud service.

**Comment by Piusn** [comment]
Where can i get the 1.13, and which visual studio can I use?

**Comment by Woland2k** [comment]
1.13 is now a dev branch available here: https://github.com/VirtoCommerce/vc-community/tree/dev
