### ISSUE TITLE
allPackages.js (PLATFORM\VirtoCommerce.Platform.Web\Scripts) out-of-sync?

### ISSUE THREAD

**Issue by jvdonk** [VirtoCommerce/vc-community#250]
Download latest release source, 2.6(b39c463), unpack.

Open in VS(make sure your NPM is up to date, see #247 ;)) so that the bower.json and package.json dependencies are restored.

Than in Task Runner Explorer, run the gulp **packAll** task, the outputted allPackages.js is different from what was distributed in source.

Is my build process wrong? Or is the distributed allPackages.js build with a different set of javascript files: bower dependencies or Platform .js files?

**Comment by eMazeika** [comment]
JavaScript is minified during the script generation process. It's ok if the generated result isn't identical. You should be worried only if the resulting allPackages.js file size is much different from the original one.
