### ISSUE TITLE
Uunnecessary Save changes dialog when browsing Notification templates

### ISSUE THREAD

**Issue by jvdonk** [VirtoCommerce/vc-community#251]
I'm just touring through my testing environment and your online demo environment and noticing some unwanted behavior that I just submitting for backlog purposes.

When browsing through the Notification templates, every time I click on another template I get a dialog informing me that changes has been made while there weren't any changes made.

![image](https://cloud.githubusercontent.com/assets/1164988/12577507/fb46dc52-c41a-11e5-90c6-24a1f4296e17.png)

**Comment by eMazeika** [comment]
fixed
