### ISSUE TITLE
Mailchimp integration?

### ISSUE THREAD

**Issue by jvdonk** [VirtoCommerce/vc-community#254]
Basically the question is how does the MailChimp integration works.

Couple of appearances of Mailchimp in the:
1) Blogposts about VirtoCommerce, stating MailChimp integration
2) Admin:MailChimp.MailingModule.Web module
3) Frontend: newsletter-form.liquid snippet

But I can't find the correlation between 2 and 3. As of 2.6 the frontend was resigned so maybe the MailChimp.MailingModule.Web is out-of-date and not used anymore in VirtoCommerce? 

If the MailChimp.MailingModule.Web is used, how is used? In the MailChimp.MailingModule.Web module there is a WebApi but it has the 
````
[ApiExplorerSettings(IgnoreApi = true)]
````
attribute so it isn't a public API?

**Comment by aartiomov** [comment]
The mailchimp module was the initial try to add integration with mailchimp. It can be used from within admin so far as it's not in the public API. It's not in public API because it's not part of the platform, it's more like integration module. We will think of how to use such an integration modules API in storefront.

**Comment by Woland2k** [comment]
There are actually two types of mailchimp integrations, one for that andrej is working and implemented as a module and another as a form in the theme that allows adding emails to the mailchimp list.

**Comment by jvdonk** [comment]
@Woland2k Exactly, as I mentioned with my 2) and 3)

So those 2 different types of integration have no business with each other and serve different purposes right?

Is nr 3) production ready? There are a couple of TODO's in it and I can't seem to figure out how to use it.

**Comment by Woland2k** [comment]
Yes, they are different ways on integrating, 2) is much more powerful as it works with mailchimp API's directly. It is just a starter, so it is easier for you to get the integration you want. Let us know if there are any issues with it.

3) should be working fine. Here are some more details: https://docs.shopify.com/manual/configuration/store-customization/communicating-with-customers/accounts-and-newsletters/get-a-mailchimp-form-action-url

**Comment by jvdonk** [comment]
Oh crap, I meant 2). If 2) was production ready and how to use it.

I read about nr 3 indeed, using the MailChimp [signup forms](http://kb.mailchimp.com/signup-forms)

Where does Shopify come in to the playfield? I don't know Shopify, should I? From the shopify link you just (and is mentioned in the frontend code) gave, the action-url I'm ending up with is a shopify URI. It confuses me because it looks like I'm sending my customers e-mailadresses to a thirdparty I don't know? :)

**Comment by Woland2k** [comment]
That is just general instructions, don't follow them exactly. But it should give you an idea how to do it.
2) it can be used, but it does have limited functionality that is easy to extend
