### ISSUE TITLE
Crippled user accounts in demo environment

### ISSUE THREAD

**Issue by jvdonk** [VirtoCommerce/vc-community#255]
There are 2 crippled user accounts in the demo environment which when clicked for editing are causing 404's because there is a space at the end of the users email address:

![image](https://cloud.githubusercontent.com/assets/1164988/12578491/8b884322-c421-11e5-87c7-b8ebefb8cc0a.png)

It's not that I cannot sleep for them being there ;) It's just that maybe the signup page is slipping invalid email addresses(which contains spaces)? The account-type of the two invalid user accounts are also unknown. Which is in itself not a valid state?

**Comment by artem-dudarev** [comment]
Cannot create such users with storefront or manager UI.
Probably they have been created by calling the API directly. I'll continue the research.

**Comment by artem-dudarev** [comment]
Yes, it was possible by calling API directly.
I've fixed this.
