### ISSUE TITLE
Search module dependency resolution issue 

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-community#268]
![image](https://cloud.githubusercontent.com/assets/7566324/12716090/d0e6d6d0-c8e6-11e5-8822-a4120b284870.png)

**Comment by cabri89** [comment]
I've the same problem with latest version, you have solution please ?

**Comment by artem-dudarev** [comment]
It looks like you have initialized the database when there was the VirtoCommerce.Search module installed, which has created this job, but this module has been removed later.
If you are not using the VirtoCommerce.Search module anymore, you can remove the job manually:

1. Open the Hangfire UI (http://localhost/admin/hangfire/recurring)
2. Remove the CatalogIndexJob

**Comment by cabri89** [comment]
CatalogIndexJob does not want to delete ...

![search](https://cloud.githubusercontent.com/assets/14344136/13106689/e5e9f2f8-d569-11e5-8bb8-d0d878c21b66.png)

**Comment by cabri89** [comment]
I had a problem with my IIS cache. I have deleted the database, rename my IIS application and It functioned.

Thanks for your help.
