### ISSUE TITLE
CMS link lists associations

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-community#272]

**Comment by Woland2k** [comment]
Why do we need images in link lists?

**Comment by tatarincev** [comment]
Profmagazines

On Tue, Feb 2, 2016 at 9:41 PM, Sasha <notifications@github.com> wrote:

> Why do we need images in link lists?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/VirtoCommerce/vc-community/issues/272#issuecomment-178781270>
> .
>



-- 
-- 

*Sincerely,Eugeney Tatarincev*

virtocommerce.com
тел. 8 (4012) 900-234
тел. 89062131253
skype: eugeney_tatarincev
et@virtoway.com

**Comment by tatarincev** [comment]
Functional requirements.

- Allow to associate with menu item any of ecommerce concrete object (category, product etc) or storefront search query (products by tags, products belongs to category etc)

- Allow to extend list of objects types available for association with menu item 

- Access to menu item  associated information on storefront to make decision how to display menu item and for navigation behavior


Aprox view of menu item association on management UI

![image](https://cloud.githubusercontent.com/assets/7566324/12843579/f4e744d8-cc02-11e5-881e-bfafd474ca80.png)

**Comment by tatarincev** [comment]
Now we have 2 main issue on UI
1. AssociatedObjectName not populated from API on UI
 2. AssociatedObjectType should be  'product' or 'category'
