### ISSUE TITLE
Ui-grid d'ont support full-width blade.

### ISSUE THREAD

**Issue by cabri89** [VirtoCommerce/vc-community#277]
Hello guys,

Ui-grid is a very good feature but, if I resize the blade in full-width. The table width don't change. 
What is the solution for an full-width ui-grid ?

Thank you for your help.

Regards,
Cabri89

**Comment by eMazeika** [comment]
fixed and will be included in ver 2.7 release

**Comment by cabri89** [comment]
Ok, sorry I didn't saw the 2.7 update.

Regards,
Cabri89
