### ISSUE TITLE
Website not showing right

### ISSUE THREAD

**Issue by Piusn** [VirtoCommerce/vc-community#29]
I deployed the latest dev branch but the site shows the default azure website

http://glamourfashionshousetwo-www.azurewebsites.net/

**Comment by Piusn** [comment]
I am using visual studio 2012 with the latest dev branch, http://glamourfashionshousetwo-www.azurewebsites.net, 
![capture-1](https://cloud.githubusercontent.com/assets/925985/5964115/9516adb6-a802-11e4-93e7-3622f84e40cb.PNG)

**Comment by Piusn** [comment]
I have also enable package restore but still cant seem to deploy the website content. Kindly advice.

**Comment by kodermax** [comment]
i could install only 1.12 version without error)

**Comment by kodermax** [comment]
I have the same errors.
Help us.

**Comment by Woland2k** [comment]
This might be due to old nuget. Please go to VS.NET Extensions and update nuget to the latest version (2.8) and rebuild the project.
