### ISSUE TITLE
Deployement of the latest version, could not load file or assembly System.Web.WebPages.Deployment

### ISSUE THREAD

**Issue by cabri89** [VirtoCommerce/vc-community#296]
Hello,

When I deploy the lastest version of VirtoCommerce in my server with your deployement [documentation](http://docs.virtocommerce.com/display/vc2devguide/Deploy+web+applications+to+dedicated+server).
I've this error. 
![error27](https://cloud.githubusercontent.com/assets/14344136/13172026/408c5e34-d6f6-11e5-9d14-64ad442f20f5.png)
But the 2.6 version works.

Thank you for your help.

Regards,
Cabri89

**Comment by cabri89** [comment]
I open VirtoCommerce.Manager.sln with VisualStudio and I rebuild the solution. Now I have this error.
![error](https://cloud.githubusercontent.com/assets/14344136/13177315/92bc4ea4-d718-11e5-800a-907b308672bb.png)

But if I launch in debug mode the platform works.

**Comment by tatarincev** [comment]
Probably you have old dlls in you manager app_data/modules folder,  try to clean this folder and rebuild solution.

**Comment by cabri89** [comment]
Yes that's it, thanks for your help.

Cabri89
