### ISSUE TITLE
Cart quantity not updating (edge case)

### ISSUE THREAD

**Issue by daveharnett** [VirtoCommerce/vc-community#301]
If you manually edit the quantity textbox of an item, and then remove focus from the text box by click a plus or minus button, then only the plus/minus operation gets recorded. Please see attached recording.

![3brhlfuv3v](https://cloud.githubusercontent.com/assets/1800996/13255548/8b00b1a4-da3e-11e5-8485-6e25ca8ad4ee.gif)

**Comment by tatarincev** [comment]
Hi @daveharnett we got this issue, thanks. Will fixed in next release.
