### ISSUE TITLE
Seo keywords should be uniquie within one tenant (catalog or store)

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-community#303]
Add complex unique index  Keyword  and Tenant  in seoUrlKeyword table 
Change storefront  resolving object by seo  functionality  should using tenant for making decision which object related to requested seo

Main limitation of using tenant (catalog id) when SEO definition:
Virtual catalog can contain products with same SEO from different physical catalogs and it leads to ambiguous result.

Probably we has agreements to using unique SEO keyword  constrain on system level. (need discuss)

**Comment by Woland2k** [comment]
We should add CatalogId to the SeoUrlKeyword table, for the most part it will solve issue with the same keyword categories having the same name/url, for instance (one category in master catalog with keyword "auto" and another in virtual catalog with keyword "auto"):

http://store1/auto
http://store2/auto

now after passing catalogid, we can get the exact category.

For the product we can pick two ways of implementing: 1 - add catalog id of the master catalog product exists in, and that is what will be used for creating a url (products must have unique keyword within a catalog) and 2 - make them unique within the whole system

I think 1 is more preferred although sometimes it can resolve in unpredictable behavior when 2 products with same keywords are added to same category in virtual catalog, however that use case is very rare, and we can add some checking for that when linking products.

**Comment by eMazeika** [comment]
#f8190ad4

**Comment by tatarincev** [comment]
Need add some unique SEO conflict warning messages when product or category SEO defined or changed and when added some links to virtual catalog or select catalog for store.

Implement smart SEO resolving on storefront side which will be used category or product relationship to store.

**Comment by tatarincev** [comment]
Unique SEO within catalog

Here it should background job will check SEO conflicts - same SEO for categories or products in virtual catalog. (SEO confilcts can be only for virtual catalog)
System should generate special PUSH notification to manager contains next information:
ObjectType, ObjectId, SEO info

User can resolve these conflicts via special UI initiated from push notification, store detail  by changing conflicting SEO within store

**Comment by eMazeika** [comment]
starting to implement simplified seo management UI based on http://hr975w.axshare.com/#p=productdetail
Postponing conflicts resolution part for now.

**Comment by Woland2k** [comment]
SEO shouldn't require any special consideration for the most products, meaning when new product is created, appropriate SEO info should be automatically generated (from product name).

**Comment by tatarincev** [comment]
it already did many year ago
06 Апр 2016 г. 17:19 пользователь "Sasha" <notifications@github.com>
написал:

**Comment by mastergonzaga** [comment]
Not sure this is the right place to comment, but if not already, please have in mind the auto generated SEO according to the languages within the project. Should be unique per language when defined and auto assign the default language if not defined
