### ISSUE TITLE
Asset container for each store 

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-community#306]
Currently all assets are placed in global container. Would be easier to manage and migrate if individual containers for each store were used.
Content Module assets should be using the same storage as assets module.
To do list:
Widget on store detail blade to navigate to asset management blade where the root is a special folder dedicated to this store.

**Comment by eMazeika** [comment]
Do you mean to remove these:
appSetting "VirtoCommerce:Storefront.AppData.Path"
and setting "VirtoCommerce.Content.StoragePath"?
