### ISSUE TITLE
hung deploing to azure

### ISSUE THREAD

**Issue by kodermax** [VirtoCommerce/vc-community#31]
I can't deploy project to azure
![1](https://cloud.githubusercontent.com/assets/590985/6086336/d55c3b84-ae51-11e4-8922-da1733aaddbc.png)

**Comment by Woland2k** [comment]
It hangs on building solution? I can't tell what is wrong by this screenshot.

**Comment by kodermax** [comment]
yes it hangs on building solution. may be i use vs 2013, can i use vs 2013?

**Comment by Woland2k** [comment]
Should be no issue building using vs 2013. Try opening it in VS.NET and building it.

**Comment by kodermax** [comment]
In VS.net that's ok. When I publish to website i have hung.

**Comment by Woland2k** [comment]
Any errors? You can send us your log file to support@virtocommerce.com if you'd like me to check.
