### ISSUE TITLE
Storefront payment method error

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-community#311]
I am getting error in (cartService.addOrUpdatePayment(payment.Id, payment.BillingAddress, payment.PaymentGatewayCode, payment.OuterId) of storefront checkoutcontroller.js file. when I am checking out with my payment module it is showing error.both payment id,outer id is coming null. I also checked with default payment it is showing same error.i didn't change anything in code

**Comment by Andrew-Orlov** [comment]
The method addOrUpdatePayment(paymentId, payment.BillingAddress, paymentGatewayCode, outerId) of cartService was changed to addOrUpdatePayment(payment). Please check the latest version.
