### ISSUE TITLE
Failure building when deploying

### ISSUE THREAD

**Issue by Piusn** [VirtoCommerce/vc-community#33]
Kindly help on the issue I am getting when deploying. The project builds successfully on visual studio

![capture](https://cloud.githubusercontent.com/assets/925985/6411191/3a8e9200-be87-11e4-88a0-6bf68d55dac1.PNG)

**Comment by Woland2k** [comment]
can you go to properties of the Presentation.Application project and check the setting for Installation Folder URL under Publish tab?
