### ISSUE TITLE
Boolean custom property do not save state

### ISSUE THREAD

**Issue by luciano-jr** [VirtoCommerce/vc-community#335]
When I create a new custom property to catalog, category, product or variation the value of field is not persisted.

The picture bellow show it

![issue virto](https://cloud.githubusercontent.com/assets/3333167/13639002/a48ed064-e606-11e5-8d9e-7ab7371c71c4.png)

At the console browser nothing is shown excepted by string "State -"

**Comment by eMazeika** [comment]
thanks for reporting, 
the value was persisted, but rendered incorrectly.
The fix will be included in the next release later this month.
