### ISSUE TITLE
Default azure successful azure creation screen showing

### ISSUE THREAD

**Issue by Piusn** [VirtoCommerce/vc-community#34]
I have downloaded the latest master branch, used visual studio 2012 to build, set the correct parameter on the deploy.ps1 file and run it.

It successfully deploys but this website url http://glamourfashionshouse-www.azurewebsites.net/ give the default azure creation screen.

Kindly help me out I have reported this issue again before

**Comment by Woland2k** [comment]
Issue should be fixed in 1.13 release.
