### ISSUE TITLE
Right to left issue

### ISSUE THREAD

**Issue by armanforghani** [VirtoCommerce/vc-community#347]
I read the documentation on how to localize Virto Commerce Manager.
I found that how i can translate phrases for my target language but please be aware that some languages such as Persian, Arabic and Hebrew are right-to-left. Therefore for these languages the theme of Virto Commerce Manager should be in right to left direction.

**Comment by tatarincev** [comment]
Arabic localization activated by adding lang-ar to body tag in main page (<body class="lang-ar"> ...
Need to find way to apply this class automatically depend on customer language preferences
