### ISSUE TITLE
Unable to Deploy to Azure - https://github.com/VirtoCommerce/vc-community/tree/webadmin

### ISSUE THREAD

**Issue by decloedtjunior** [VirtoCommerce/vc-community#35]
the server responded with a status of 500 (Internal Server Error)

"Unable to translate bytes [F3] at index 22 from specified code page to Unicode."

System.Text.DecoderFallbackException: Unable to translate bytes [F3] at index 22 from specified code page to Unicode. at System.Text.DecoderExceptionFallbackBuffer.Throw(Byte[] bytesUnknown, Int32 index) at System.Text.DecoderExceptionFallbackBuffer.Fallback(Byte[] bytesUnknown, Int32 index) at System.Text.DecoderFallbackBuffer.InternalFallback(Byte[] bytes, Byte* pBytes, Char*& chars) at System.Text.UTF8Encoding.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, DecoderNLS baseDecoder) at System.Text.DecoderNLS.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, Boolean flush) at System.Text.DecoderNLS.GetChars(Byte[] bytes, Int32 byteIndex, Int32 byteCount, Char[] chars, Int32 charIndex, Boolean flush) at System.Text.DecoderNLS.GetChars(Byte[] bytes, Int32 byteIndex, Int32 byteCount, Char[] chars, Int32 charIndex) at System.IO.StreamReader.ReadBuffer(Char[] userBuffer, Int32 userOffset, Int32 desiredChars, Boolean& readToUserBuffer) at System.IO.StreamReader.Read(Char[] buffer, Int32 index, Int32 count) at Newtonsoft.Json.JsonTextReader.ReadData(Boolean append, Int32 charsRequired) at Newtonsoft.Json.JsonTextReader.ParseValue() at Newtonsoft.Json.JsonTextReader.ReadInternal() at Newtonsoft.Json.JsonTextReader.Read() at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) at System.Net.Http.Formatting.JsonMediaTypeFormatter.<>c__DisplayClass8.<ReadFromStreamAsync>b__6() at System.Threading.Tasks.TaskHelpers.RunSynchronously[TResult](Func`1 func, CancellationToken cancellationToken) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at Slingshot.Controllers.ARMController.<GetTenantsArray>d__67.MoveNext() in c:\code\GitHub\slingshot\Slingshot.Api\Controllers\ARMController.cs:line 436 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at Slingshot.Controllers.ARMController.<GetTemplate>d__4c.MoveNext() in c:\code\GitHub\slingshot\Slingshot.Api\Controllers\ARMController.cs:line 334

**Comment by codepic** [comment]
I managed to get deployment working with the following steps

1. Deploy to Azure from https://github.com/VirtoCommerce/vc-community/tree/webadmin
2. Deployment fails, leave the browser tab as it is...
3. Open new tab and go to https://portal.azure.com > Find the failed deployment > Redeploy
4. Continue deployment on https://deploy.azure.com/?repository=https://github.com/VirtoCommerce/vc-community/tree/webadmin#/form/deploy

**Comment by artem-dudarev** [comment]
This is due to a bug in Azure API, which returns invalid JSON if Azure directory name contains Uncode characters. In this case the name was Diretório Padrão.
The deployment wizard developers added a workaround for this problem and the error is gone but you still can see the '�' characters in the directory name instead of real Unicode characters.

@codepic described a different problem because before adding a workaround the deployment wizard didn't show even the first step with the setup form, so it was impossible to start the deployment process.
