### ISSUE TITLE
Reinstate social login to the storefront.

### ISSUE THREAD

**Issue by gerfen** [VirtoCommerce/vc-community#350]
Social login is not available on the storefront. This is blocking issue.  Please reinstate this functionality.  Please provide a way to configure using only social logins for registration and logging into the store front.

**Comment by tatarincev** [comment]
Will be reinstate on this week.

**Comment by gerfen** [comment]
Thank you.  Will that be rolled into the vc-community dev branch?  If so, can you make an announcement via Gitter?
