### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by ludlamzgull** [VirtoCommerce/vc-community#353]
Guys i am hoping you can help me.

Followed all the instructions one by one, this is the latest revision of master branch.
![image](https://cloud.githubusercontent.com/assets/550732/13828507/c30ccf92-ebb9-11e5-8885-1b6773c3dc17.png)

**Comment by Woland2k** [comment]
Make sure the whole solution (VirtoCommerce.Manager.sln) is compiled and Modules folder is created in correct place under IIS.

From the error, it seems you didn't compile the solution.
