### ISSUE TITLE
404 error - Link to Categories

### ISSUE THREAD

**Issue by IT4Solution** [VirtoCommerce/vc-community#372]
Hi, all the categories links have some routing problem.
I am using the last master version.

Thank you in advance

![error](https://cloud.githubusercontent.com/assets/10602250/14152138/ea572db2-f687-11e5-86c6-4e78784ab6ce.png)
![main](https://cloud.githubusercontent.com/assets/10602250/14152137/ea56d632-f687-11e5-93ab-1e30b23dc194.png)

**Comment by tatarincev** [comment]
Continue communication via help desk
