### ISSUE TITLE
Error on startup as data is not getting generated

### ISSUE THREAD

**Issue by adageamar** [VirtoCommerce/vc-community#384]
I am new to this, and I had created a database and when I run the application, the 21 tables got created but when I login and it will ask to empty data or with data and I select the data, it is completed with 55MB but after that will get error as 

Error resolving type specified in JSON 'VirtoCommerce.StoreModule.Web.Security.StoreSelectedScope, VirtoCommerce.StoreModule.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Path 'Users[5].Roles[1].Permissions[0].AssignedScopes.$values[0].$type', line 101, position 175. Could not load assembly 'VirtoCommerce.StoreModule.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by tatarincev** [comment]
Which VC version you use?

**Comment by adageamar** [comment]
I had cloned from git hub so its new I guess.

**Comment by tatarincev** [comment]
Can you drop database and reset IIS and try to open manager again in browser and sen me screenshot of sample data popup

**Comment by adageamar** [comment]
I had dropped the database and recreated it, Now when I run the application, It shows me login screen, I login using Admin user and selected Clothing and Electronics

![virtocommerce](https://cloud.githubusercontent.com/assets/7877493/14389447/4a380b08-fdd0-11e5-8d53-198b4e603052.png)

Sample Data Initialization
![virtocommerce1](https://cloud.githubusercontent.com/assets/7877493/14389485/7a57206c-fdd0-11e5-959d-0759982f3bb6.png)

After completing 55MB getting following error.
![virtocommerce2](https://cloud.githubusercontent.com/assets/7877493/14390190/87b1791c-fdd3-11e5-8f3c-33e5fa41e139.png)

The complete error is 
Error resolving type specified in JSON 'VirtoCommerce.StoreModule.Web.Security.StoreSelectedScope, VirtoCommerce.StoreModule.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Path 'Users[5].Roles[0].Permissions[2].AssignedScopes.$values[0].$type', line 119, position 175. Could not load assembly 'VirtoCommerce.StoreModule.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

**Comment by tatarincev** [comment]
You have not correct IIS configuration and Modules folder mapping. Please read this article http://docs.virtocommerce.com/display/vc2devguide/Source+Code+Getting+Started
