### ISSUE TITLE
Category not updated when importing existing product

### ISSUE THREAD

**Issue by Esbob** [VirtoCommerce/vc-community#39]
While using the catalog import function, I've noticed that I can update the name of an existing product and properties such as brand and visibility in store if I import the product using its existing unique ID, which is great. Unfortunately, I can't change its category. I have to delete the product from the database first and then import it, in order to get the category that I indicated in my CSV file. I would expect to be able to update all the properties of a product except for its unique ID(s).

**Comment by tatarincev** [comment]
Hi, we will certainly fix it as soon as possible
Thanks for you request.

**Comment by tatarincev** [comment]
Hi, we already did that feature.

**Comment by Esbob** [comment]
When was it fixed? I found this bug on the dev branch 2 days ago.

**Comment by tatarincev** [comment]
It fixed today.

**Comment by Esbob** [comment]
Great - thanks :-)
