### ISSUE TITLE
Notification edit screen languages are hard coded

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-community#393]
Need to make sure the languages are taken from settings instead of being hard coded:

https://github.com/VirtoCommerce/vc-community/blob/dev/PLATFORM/VirtoCommerce.Platform.Web/Scripts/app/notifications/blades/notifications-edit-template.js

**Comment by tatarincev** [comment]
https://github.com/VirtoCommerce/vc-community/commit/1ba6fb93df9105defca7ac80ccb2533469315794
