### ISSUE TITLE
Assets from subfolder are not served correctly

### ISSUE THREAD

**Issue by attilah** [VirtoCommerce/vc-community#399]
I've a problem. If I've subfolder under my assets folder the resources are not served, instead the index page is returned for a given asset.

```
assets/css/bootstrap.min.css <- not working
assets/bootstrap.min.css <- working
```

Liquid to generate the link:
```
{{ 'css/bootstrap.min.css' | asset_url | stylesheet_tag }}
```

When loading the page I see this in the browser, since VC is serving HTML for a CSS url:
Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://www.nannidev.com/en-US/themes/assets/css/bootstrap.min.css".

If I move out the file from the css subdirectory, everything works, but having all the files in 1 directory is a mess in long term.
 
It is on latest dev.

**Comment by artem-dudarev** [comment]
Fixed.
