### ISSUE TITLE
error in detail page

### ISSUE THREAD

**Issue by kodermax** [VirtoCommerce/vc-community#40]
I installed virtocommerce and got error
![image](https://cloud.githubusercontent.com/assets/590985/8397280/19002da4-1dcf-11e5-83bc-1eb5a96b91a2.png)

this page has error http://localhost:55342/samplestore/vendorvirtual-audio-mp3/sony-walkman-nwz-e354-8gb-digital-music-player-(blue)

**Comment by kodermax** [comment]
![image](https://cloud.githubusercontent.com/assets/590985/8397285/3541065a-1dcf-11e5-92c3-ebcb5d6d4131.png)

**Comment by Woland2k** [comment]
thanks for the screenshot, the issue should be fixed in the latest code
