### ISSUE TITLE
PayPal Invalid HTTP response

### ISSUE THREAD

**Issue by luciano-jr** [VirtoCommerce/vc-community#401]
After the payment process in checkout I've this message response in orderProcessingResult var: 

"Invalid HTTP response: The request was aborted: Could not create SSL/TLS secure channel"

I have used this configuration:

![paypalbug](https://cloud.githubusercontent.com/assets/3333167/14600108/f6ab870a-0552-11e6-939d-52f73496b723.png)

**Comment by Andrew-Orlov** [comment]
I have a suggestion that PayPal has changed their API and code of PayPal VC-module is no longer actual. Please check [this solution on StackOverflow](http://stackoverflow.com/a/34946494/4572379) while we working on this issue.

**Comment by luciano-jr** [comment]
@Andrew-Orlov ok, thank you!
