### ISSUE TITLE
admin doesn't work

### ISSUE THREAD

**Issue by kodermax** [VirtoCommerce/vc-community#41]
I installed virtocommerce,
when i try admin:store, i get error.
http://c2n.me/3lS1HAS

        <title>The process cannot access the file 'C:\Sites\vc-community\PLATFORM\VirtoCommerce.Platform.Web\AvaTax.log' because it is being used by another process.</title>

**Comment by aartiomov** [comment]
The issue is fixed. You can use the latest code from the dev branch. Another option is to uninstall avalara module if you don't need it.
