### ISSUE TITLE
Tiered Prices not reflected in shopping Cart.

### ISSUE THREAD

**Issue by DaleCam** [VirtoCommerce/vc-community#410]
Steps to replicate:
Add tiered prices to a products Pricing List.
Go back as a Store user, and add the product to a shopping cart.
View the cart, and increase the quantity of the product until the product should enter a new tiered price.

![capture1](https://cloud.githubusercontent.com/assets/4400216/14697876/ed53e696-074d-11e6-9995-568536939d93.PNG)
![capture2](https://cloud.githubusercontent.com/assets/4400216/14697893/161846c6-074e-11e6-832d-7849361d13a1.PNG)
-----------------
Result is that the cart displays the cheapest tier regardless of the quantity, instead of the quantity based tiered price.

**Comment by tatarincev** [comment]
Current storefront model type CatalogPrice  have a TirePrice collection but it s newer populated and used. I think its good day to do it :)
