### ISSUE TITLE
Simplify inner storefront routing (force convert  url to full store/language/path sctructure)

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-community#412]
Get rid 3-x diff types routes for each route
Allow to resolve static content routing issue : localhost/features/for-business-professionals
where features interpret as store and for-business-professionals interpret as path

**Comment by Woland2k** [comment]
All different paths need to work, for example without a store, without a language and so on. One preferred path should be displayed to a user however, redirecting user to the primary path.

**Comment by tatarincev** [comment]
Made StorefrontUrlRewriterOwinMiddleware owin middleware normalizing all requests path to {store}/{language}/{path} request schema.
 
Left making redirect  for GET requests if requested path have other primary path. (specified  or missed store, lang  path parts)
