### ISSUE TITLE
clear demo content

### ISSUE THREAD

**Issue by kodermax** [VirtoCommerce/vc-community#42]
Please add function:
clear demo catalog.

**Comment by tatarincev** [comment]
Hi, thanks for suggestion
Currently you can dissable sample data instalation by change web.config 
`<add key="VirtoCommerce:SampleDataLevel" value="None" />`
In next release we add more advanced sample data management functionality.

**Comment by tatarincev** [comment]
In 2.4 version we added sample data discovery functionality. You can choose appropriate sample data template when you first start the syste
