### ISSUE TITLE
Filter properties don't work

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-community#421]
<img width="1574" alt="screen shot 2016-04-27 at 6 52 17 pm" src="https://cloud.githubusercontent.com/assets/1566470/14873251/49c8f53c-0ca9-11e6-8a71-6d2ad10c5245.png">

**Comment by tatarincev** [comment]
Its demo sample data security issue

**Comment by Woland2k** [comment]
It should never give such error
