### ISSUE TITLE
DevProcesses - Modules storage infrastructure redesign

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-community#428]
Create public github repository for each VC module. (each repository name  should have some special suffix or prefix)
for each module write readme.md contains module description, authors, features, installation and other information
Release automation:
release notes (automation)
1. Module source code
2. Module VC zip package generation (first time can be done manually)
3. Module server SDK libraries generation and publishing in public nuget repository as nuget package.
4. Module nuget client SDK generation and publishing (based on swagger doc) 

VC update server virtocommerce/apps should get information directly from github modules repositories 
Know problems:
Swagger docs for concrete module
Need preserve change history log

**Comment by Woland2k** [comment]
vc-module-{module-name} for the module repository
