### ISSUE TITLE
DevProcesses - VirtoCommerce update service

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-community#429]
Use virtocommerce/apps already exist application
which should used github modules and platform repositories as primary data source.
Should expose search API for using multiple platform instances as update service.
Should return follow module information:
Module dependencies
Module zip packages link
Descriptions and authors
nuget packages links (server and clients)

**Comment by Woland2k** [comment]
here is an example of update json: http://updates.jenkins-ci.org/update-center.json
