### ISSUE TITLE
DevProcesses - Platform advanced module management and updates UI prototype

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-community#430]
Key requirements:
   List of all installed and available for installation modules (using VC update service)
   Modules search, grouping and sorting, categorization, display some statistic
   Possibility to install module from remote source with automatically dependency resolving (display information for all depend modules)
   Possibility to uninstall module with all dependencies (display information for all dependencies)
   Update platform and installed modules from remote service (informing about new versions)
   Version validation preventing to install incompatible components

delay restart after installation 
modules presets (bundles)  support (with more detailed description)

**Comment by eMazeika** [comment]
wireframe: http://hr975w.axshare.com/module-list.html

**Comment by Woland2k** [comment]
The top tab choices should be: updates, available, installed, advanced.

In the "Updates" list, column "Version" should be renamed to "Installed" and "Latest Version" to "Version".

In the installed list, it should have checkbox-es next to installed (should only be able to uninstall modules that have no external dependencies within other modules). Also should allow to downgrade to the previously installed version of the module (not the previous release).

**Comment by eMazeika** [comment]
Wireframe updated. The support of bulk uninstall and version downgrade is not planned at the moment.

**Comment by Woland2k** [comment]
downgrade must be supported, otherwise it would be impossible to revert to the last stable version.

Also need support for upgrading platform itself, not just modules.
