### ISSUE TITLE
DevProcesses - Platform advanced module management and updates - back-end changes

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-community#431]
List of all available  for installation modules
   Modules search, grouping and sorting, categorization
   Possibility to install module from remote source with automatically dependency resolving (install with all dependencies)
   Possibility to uninstall module with all dependencies
   informing about new versions
   Update platform and installed modules from remote update service
   Version validation preventing to install incompatible components
   Modules isolation (preventing crashing whole system)

**Comment by Woland2k** [comment]
Here is example of json containing updates: http://updates.jenkins-ci.org/update-center.json
