### ISSUE TITLE
Packaging issue

### ISSUE THREAD

**Issue by kassemshehady** [VirtoCommerce/vc-community#44]
Package is not generated correctly
![unnamed](https://cloud.githubusercontent.com/assets/3023747/9382329/8b0eea96-4748-11e5-83b1-dcb0358c803d.png)

**Comment by artem-dudarev** [comment]
We need a detailed log of the build process.
To create the log please change the verbosity value in pack_modules.cmd to __diag__:
```
:: 2. Build to the temporary path
call :ExecuteCmd "%MSBUILD_PATH%" "%PROJECT_FILE%" /nologo /verbosity:diag
```
Then call the pack_modules.cmd for single module and redirect output to pack.txt:
```
pack_modules.cmd PLATFORM\Modules\Core\VirtoCommerce.Core.Web\VirtoCommerce.CoreModule.Web.csproj > pack.txt
```
Then send us the resulting pack.txt.
