### ISSUE TITLE
Liquid global variable 'collection.url' returns different formatting than store SEO link setting

### ISSUE THREAD

**Issue by Esbob** [VirtoCommerce/vc-community#441]
I've set my store to use _Short_ SEO links (Store -> Settings -> SEO Links), but when I use the global variable **collection.url** from within a Liquid template, it returns a category URL formatted as option _None_, not _Short_ as I would expect. I believe the Liquid global variables need to follow the SEO links formatting chosen.

**Comment by tatarincev** [comment]
Please check that your category has a SEO slug.
09 Май 2016 г. 18:20 пользователь "Esben Visfeldt" <notifications@github.com>
написал:

**Comment by Esbob** [comment]
It does :-)

**Comment by tatarincev** [comment]
Collection.Url should contains slug url depend on Store setting (Full, Short, none). Can you send you catalog export data to attempt repeat you problem locally?

**Comment by Esbob** [comment]
You can easily reproduce it with the sample Clothing store, which by default uses long SEO links: Edit e.g. the matherial snippet 'breadcrumb.liquid', insert _{{collection.url}}_ and navigate to a category such as day dresses:
http://mysite/Clothing/day-dresses (with a store link set to http://mysite/Clothing)
In my case the output is: '~/category/33505982c1134ff5b10c7a461f10a4cb' but I expected '~/day-dresses'

**Comment by artem-dudarev** [comment]
Outlines are required for building long SEO links but this collection was not filled because CategoryResponseGroup was missing the WithOutlines flag.
Here is the fix:
https://github.com/VirtoCommerce/vc-community/commit/a9e8256cbeed1105a0f84c1b5397430bb4ec656d

**Comment by Esbob** [comment]
Thanks for your quick response :-)
I'll install the dev branch and try it on my own later on.

**Comment by Esbob** [comment]
It works - thanks!
