### ISSUE TITLE
[2.11] New platform/module structure?

### ISSUE THREAD

**Issue by jvdonk** [VirtoCommerce/vc-community#444]
Hi,

Care to elaborate a bit more on the upcoming 'epic' devprogress changes? Looks promising for custom VC platform solutions.

I'm about to setup a VC platform solution with custom modules and currently very few core modules(only the swashbuckle module for now). No storefront, but probably a custom client using the SDK client to connect to the API. 

We currently use TeamCity/Octopus Deploy in our build/deploy pipeline and I saw some nuget related 'issues' together with the 'epic DevProgress' issues and felt the urge to see if there is a bit more info available on this subject. :) Thanks!

**Comment by tatarincev** [comment]
Just bring a few key aspects for future dev process reorganization:
1. Platform and modules will be live in separate repositories with own versions and separated releases.
2. virtocommerce.com/apps will be working as  update server getting information about new releases from these repositories
3. client VC platform instances will be updated automatically/manually thought  build in UI (similar to nuget Visual studio interface)
4. developers will be develop custom solutions and modules without platform source code  by using nuget packages for platform and modules libraries (each module will be expose three assets 1. VC zip module package to install in manager via UI or update server, 2. nuget package contains SDK libraries for devvelopment, 3. nuget packages contains  API client code)

More process details can see in data flow diagrams attached to the epic tickets.

**Comment by jvdonk** [comment]
Thank you for your add-on, I will keep following the epic issues.

Will the virtocommerce.com/apps updating server be opensource as well?

**Comment by Woland2k** [comment]
Yes, the apps store will be open source, but it won't be needed to setup your own update server as it will be driven by a simple JSON file containing info on all modules available.
