### ISSUE TITLE
the Item.Weight is not set ShippingContext.ShoppingCart

### ISSUE THREAD

**Issue by alexdoan102** [VirtoCommerce/vc-community#446]
the [Item.Weight] is not set using ShippingContext.ShoppingCart.
 ==> I am coding a custom shipping module, but the weight is not set for the item using teh ShippingEvaluationContext.ShoppingCar.

**Comment by tatarincev** [comment]
Need to add weight and 'weight unit' input fields to 'physical' product detail blade. 'Weight unit' should be a editable dictionary defined as setting (similar to TaxTypes etc). After this user will be able to set weight for products and its will be sets for cart line items.

**Comment by alexdoan102** [comment]
the default electronic store has "weight" for the cellphones, but it does not have "weight"unit.. are you saying i should add this..and it will work??? please advise. thx.

**Comment by Woland2k** [comment]
alex, this is for egis to implement feature, not for you to just add extra property

**Comment by eMazeika** [comment]
fields added: https://github.com/VirtoCommerce/vc-community/commit/034f88f7bfeea41d9083b3a8a065eb45d59f4b2b

**Comment by alexdoan102** [comment]
the [Weight] is still not set correctly.  The [WeightUnit"] is working, i get the ounce or pound.  But the [Weight] is still not set correctly...it is always "0".  I tried with different products in the electronics example.   ( i restarted IIS several times.) .  Please advise.   
![b6_weightuni_try2](https://cloud.githubusercontent.com/assets/73307/15268417/da6b835c-19ab-11e6-8c91-cfb14c88894d.png)

**Comment by alexdoan102** [comment]
you also need [length, width,height] , and also "Prepackage Type" ==> need 4 more fields
==> USPS, FEDEX, UPS, DHL needs these fields as well. can you please add these fields as well?? thx!
![b6_weightuni_try3](https://cloud.githubusercontent.com/assets/73307/15268719/85f1c43e-19b6-11e6-9303-61f90e7714ae.png)

**Comment by tatarincev** [comment]
#446 commit contain fix with weight issue.
Dimension fields and 'Prepackage Type' to product details blade UI will be added little later.

**Comment by tatarincev** [comment]
Dimensions should assigned to products only as Prepackage Type. Prepackage types will be managed separate and only there related with concrete dimensions.

**Comment by alexdoan102** [comment]
Shipping is not done correctly with the ShipStation module ==> this is jut a module to do shiiping fullfilment, and not calculate shipping rates at all for the shipping cart.  The shipstation API does have method to calc shipping, but I need the Dimensions added so i can fix the API. Also, the Shipstation API is old and not as good as www.easypost.com ==> better developer API.
  Can you please add the Dimension fields ASAP?  i cannot code the shipping module without this. thx!

**Comment by alexdoan102** [comment]
![b6_weightuni_try4](https://cloud.githubusercontent.com/assets/73307/15405529/435555b4-1dd0-11e6-9105-3d7ebd2d7d87.png)
the weight is still not set correctly.

**Comment by alexdoan102** [comment]
as per commit 19cc9a7   ==> the weight is still not set

**Comment by alexdoan102** [comment]
nvm @tatarincev bug#446, commit 19cc9a7, the weight is working.... (i forgot to recompile the storefront)..
