### ISSUE TITLE
İnstalling to Local Machine Problem System.Data.SqlClient.SqlException: Invalid column name 'id'.

### ISSUE THREAD

**Issue by barisakpunar** [VirtoCommerce/vc-community#45]
When installing the solution there is an sql migration error as follows;

Server Error in '/admin' Application.

Invalid column name 'id'.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Data.SqlClient.SqlException: Invalid column name 'id'.

Source Error: 

Line 47:                 try
Line 48:                 {
Line 49:                     migrator.Update();
Line 50:                 }
Line 51:                 catch (SqlException ex)

Source File: c:\vc-community-master\PLATFORM\VirtoCommerce.Platform.Data\Infrastructure\SetupDatabaseInitializer.cs    Line: 49 

Stack Trace: 

[SqlException (0x80131904): Invalid column name 'id'.]
   System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) +388
   System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) +717
   System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) +4515
   System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite) +1387
   System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite) +533
   System.Data.SqlClient.SqlCommand.ExecuteNonQuery() +287
   System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch(TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed) +208
   System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext) +438
   System.Data.Entity.Migrations.DbMigrator.ExecuteSql(DbTransaction transaction, MigrationStatement migrationStatement, DbInterceptionContext interceptionContext) +202
   System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbTransaction transaction, DbInterceptionContext interceptionContext) +98
   System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection) +780
   System.Data.Entity.SqlServer.<>c__DisplayClass1.<Execute>b__0() +15
   System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute(Func`1 operation) +263
   System.Data.Entity.Migrations.DbMigrator.ExecuteStatements(IEnumerable`1 migrationStatements, DbTransaction existingTransaction) +377
   System.Data.Entity.Migrations.DbMigrator.ExecuteOperations(String migrationId, XDocument targetModel, IEnumerable`1 operations, IEnumerable`1 systemOperations, Boolean downgrading, Boolean auto) +1170
   System.Data.Entity.Migrations.DbMigrator.ApplyMigration(DbMigration migration, DbMigration lastMigration) +748
   System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId) +169
   System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase) +1134
   VirtoCommerce.Platform.Data.Infrastructure.SetupDatabaseInitializer`2.InitializeDatabase(TContext context) in c:\vc-community-master\PLATFORM\VirtoCommerce.Platform.Data\Infrastructure\SetupDatabaseInitializer.cs:49

[ApplicationException: Migrations failed with error "Invalid column name 'id'."]
   VirtoCommerce.Platform.Data.Infrastructure.SetupDatabaseInitializer`2.InitializeDatabase(TContext context) in c:\vc-community-master\PLATFORM\VirtoCommerce.Platform.Data\Infrastructure\SetupDatabaseInitializer.cs:63
   VirtoCommerce.CatalogModule.Web.Module.SetupDatabase() in c:\vc-community-master\PLATFORM\Modules\Catalog\VirtoCommerce.CatalogModule.Web\Module.cs:39
   VirtoCommerce.Platform.Core.Modularity.ModuleInitializer.Initialize(ModuleInfo moduleInfo) in c:\vc-community-master\PLATFORM\VirtoCommerce.Platform.Core\Modularity\ModuleInitializer.cs:60

[ModuleInitializeException: An exception occurred while initializing module 'VirtoCommerce.Catalog'.]
   VirtoCommerce.Platform.Core.Modularity.ModuleInitializer.HandleModuleInitializationError(ModuleInfo moduleInfo, Exception exception) in c:\vc-community-master\PLATFORM\VirtoCommerce.Platform.Core\Modularity\ModuleInitializer.cs:122
   VirtoCommerce.Platform.Core.Modularity.ModuleInitializer.Initialize(ModuleInfo moduleInfo) in c:\vc-community-master\PLATFORM\VirtoCommerce.Platform.Core\Modularity\ModuleInitializer.cs:65
   VirtoCommerce.Platform.Core.Modularity.ModuleManager.InitializeModule(ModuleInfo moduleInfo) in c:\vc-community-master\PLATFORM\VirtoCommerce.Platform.Core\Modularity\ModuleManager.cs:343
   VirtoCommerce.Platform.Core.Modularity.ModuleManager.LoadModulesThatAreReadyForLoad() in c:\vc-community-master\PLATFORM\VirtoCommerce.Platform.Core\Modularity\ModuleManager.cs:229
   VirtoCommerce.Platform.Core.Modularity.ModuleManager.LoadModuleTypes(IEnumerable`1 moduleInfos) in c:\vc-community-master\PLATFORM\VirtoCommerce.Platform.Core\Modularity\ModuleManager.cs:210
   VirtoCommerce.Platform.Core.Modularity.ModuleManager.LoadModule(String moduleName) in c:\vc-community-master\PLATFORM\VirtoCommerce.Platform.Core\Modularity\ModuleManager.cs:115
   VirtoCommerce.Platform.Web.Startup.Configuration(IAppBuilder app) in c:\vc-community-master\PLATFORM\VirtoCommerce.Platform.Web\Startup.cs:114

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +76
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +211
   System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) +35
   Owin.Loader.<>c__DisplayClass1.<LoadImplementation>b__0(IAppBuilder builder) +341
   Microsoft.Owin.Host.SystemWeb.OwinAppContext.Initialize(Action`1 startup) +1043
   Microsoft.Owin.Host.SystemWeb.OwinHttpModule.InitializeBlueprint() +119
   System.Threading.LazyInitializer.EnsureInitializedCore(T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory) +241
   Microsoft.Owin.Host.SystemWeb.OwinHttpModule.Init(HttpApplication context) +129
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +530
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +304
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +404
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +475

[HttpException (0x80004005): Exception has been thrown by the target of an invocation.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +12618692
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +159
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +12458309

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.34249

**Comment by Woland2k** [comment]
Hi,
do you already have VirtoCommerce database already created? If so, delete the database and restart IIS and see if that fixes it.

**Comment by artem-dudarev** [comment]
Cannot reproduce this error neither with master (2.4.561) nor with dev (2.4.566) source code.
Also your stack trace has error at line 39 of VirtoCommerce.CatalogModule.Web\Module.cs, but this line doesn't belong to SetupDatabase() method. Probably you made some changes to the code.
Please check if unmodified latest code still has the issue.
