### ISSUE TITLE
Add Vendor/Supplier error ==> cannot add vendor/supplier to product:  

### ISSUE THREAD

**Issue by alexdoan102** [VirtoCommerce/vc-community#450]
Add Vendor/Supplier error ==> cannot add vendor/supplier to product:  
![b8_addsuppliererror](https://cloud.githubusercontent.com/assets/73307/15271261/e67aa8be-1a0d-11e6-98fc-d380a6e9490f.png)

**Comment by tatarincev** [comment]
Same reason as in  https://github.com/VirtoCommerce/vc-community/issues/452
