### ISSUE TITLE
In debug Mode with VisualStudio ==> when you create an order ==> you get a "Supplier" is null during the creation of the order

### ISSUE THREAD

**Issue by alexdoan102** [VirtoCommerce/vc-community#451]
In debug Mode with VisualStudio ==> when you create an order ==> you get a "Supplier" is null during the creation of the order... if u step pass that exception, it will create the order...but the debugger is showing Null Exception for Supplier for order creation

**Comment by tatarincev** [comment]
Same reason as in https://github.com/VirtoCommerce/vc-community/issues/452
