### ISSUE TITLE
avalara tax module does not work ==> taxevaluation context is not set correctly

### ISSUE THREAD

**Issue by alexdoan102** [VirtoCommerce/vc-community#453]
avalara tax module does not work ==> taxevaluation context is not set correctly
 ==> the taxevaluationcontext.Address & taxevaluationcontext.Customer  are BOTH NULL.
       ==> since they are both NULL the avalara service is not called at all.

![c1_taxevalcontext_avalara](https://cloud.githubusercontent.com/assets/73307/15271552/e117bdd4-1a1d-11e6-9061-87ed3759a112.png)

**Comment by aartiomov** [comment]
Hi, I'm developer of the Avalara module. It seems that TaxEvaluationContext has changed recently. Let us check and look for the solution asap.
Thanks.

**Comment by Woland2k** [comment]
@aartiomov can we make sure to include some xunit tests for avalara so such error can be cought during automated tests?

**Comment by alexdoan102** [comment]
@tatarincev @aartiomov , I created PULL Request #479 . This fixes that the address and customerid so that the avalaraTax module would execute.
However, the avalara service calls returns "At least one address or LocationCode is required. Address is incomplete or invalid.". I verified that I am sending the correct address. (see screenshot). Please advise.
![avalarabug](https://cloud.githubusercontent.com/assets/73307/15662316/6b6ea44c-26bd-11e6-96c8-d0227d967ab3.png)

**Comment by alexdoan102** [comment]
Set the attached [avalaraRequest_ObjectDump.txt] file for Request dump of object.

I am still getting invalid address (even with region = PA)

[avalaraRequest_ObjectDump.txt](https://github.com/VirtoCommerce/vc-community/files/292547/avalaraRequest_ObjectDump.txt)

**Comment by alexdoan102** [comment]
I manually calculated the address/tax in the avalara Tax portal...and it works.... but calling through your service does not work.

![avalaramanualcalc](https://cloud.githubusercontent.com/assets/73307/15696819/356fdeae-2782-11e6-9e4b-bba608c6085e.png)

**Comment by aartiomov** [comment]
AvaTax modified the Postal code "19142" -> "19142-2409". Can you provide the postal code Avalara has set after validation and try with it?
Anyway will add tests to the module in order to keep it up to date with the later releases.

**Comment by alexdoan102** [comment]
new dump file of request.. ==> changing to use long zipcode  "19142-2409" , still same error..address invalid.

[avalaraRequest_ObjectDumpv2.txt](https://github.com/VirtoCommerce/vc-community/files/293720/avalaraRequest_ObjectDumpv2.txt)

**Comment by alexdoan102** [comment]
the [AddressCode] is not set correctly for the TaxRequestConverter in the [TaxDetailConverter.cs] file.
The eval uses the "Shipping" for AddressCode ==> the but AddressCode has to match the Index you are using. (you have it correct for the [CustomerOrderConverter.cs] and the [ShoppingCartConverter.cs],  but the regular [TaxRequestConverter] is wrong. (see screenshot below)

![avalaraaddresscode](https://cloud.githubusercontent.com/assets/73307/15724628/e80f66ae-2815-11e6-870a-f412a2f0c5e5.png)

**Comment by aartiomov** [comment]
Commited the fix and added test for that method.
