### ISSUE TITLE
[Hangfire] configuration

### ISSUE THREAD

**Issue by jvdonk** [VirtoCommerce/vc-community#454]
Given the recommended network configuration for VC:
![image](https://cloud.githubusercontent.com/assets/1164988/15313025/b500816c-1c08-11e6-8048-142445e63938.png)

It splits the queuing and processing of background jobs into two processes right? So to set this up one need to have two instances of the Platform(Manager solution?) running. One of them with the Jobs.Enabled configuration on true and one of them on false?
````
<add key="VirtoCommerce:Jobs.Enabled" value="true" />
````

If I have two web apps running, one with the Jobs.Enabled on false, what about the UI and API portion of this webapp? Is it also available but not used? Does one need to configure more options or disable them?

And the Hangfire storage type on SqlServer?

Also, the documentation mentions Redis as hangfire storage, though I cannot find the supporting code base for this. Is it not used anymore beause only Hangfire Pro supports Redis storage?

**Comment by artem-dudarev** [comment]
Splitting the manager webapp is recommended to reduce the background jobs influence on UI and API responsiveness. This also applies to using Redis as a shared storage for jobs.

The webapp with Jobs.Enabled=false is the main app, it provides UI, API and schedules jobs, which are stored in the shared storage (SQL, Redis, etc.). Actually it does everything except running jobs.
The webapp with Jobs.Enabled=true takes jobs from the shared storage and executes them.

Currently the HangfireLauncher implementation supports SqlServer and Memory storage types and using Redis requires some coding and/or switching to Redis Pro, but it is still much better than using SQL database which is quite slow and expensive.

**Comment by jvdonk** [comment]
Doesn't "The webapp with Jobs.Enabled=true" also provides UI and API? Though they aren't used because the routes aren't never called(but they can be).

2 webapps:
1) mainapp.myurl.com (Jobs.Enabled=false)
2) hangfire.myurl.com (Jobs.Enabled=true)

On both 1) and 2) /api routes are active right? Same for /#/login(the UI(manager))

**Comment by artem-dudarev** [comment]
Yes, UI and API are active but should not be used.
