### ISSUE TITLE
Product Description is not rendered as html in storefront

### ISSUE THREAD

**Issue by Dhiren-K** [VirtoCommerce/vc-community#455]

**Comment by eMazeika** [comment]
provide some details, please

**Comment by Dhiren-K** [comment]
<p><a class="c27 fs22">Performance</a></p>
<p> Maximum Speed  55 mph / 88.5 km/h  Maximum Altitude  400' / 121.9 m AGL  Flight Time  Up to 25 minutes (20 with camera and Solo Gimbal) </p>
<table class="specTable" border="1"><tbody><tr><th class="specHeader Header" colspan="2"><a class="c27 fs22">Flight Control System</a></th></tr><tr><td class="specTopic c28 fs14 bold"> Model </td><td class="specDetail c28 fs14"> Pixhawk 2 </td></tr><tr><td class="specTopic c28 fs14 bold"> Software </td><td class="specDetail c28 fs14"> APM flight control software </td></tr><tr><td class="specTopic c28 fs14 bold"> GPS </td><td class="specDetail c28 fs14"> Yes </td></tr></tbody></table>
<table class="specTable" border="1"><tbody><tr><th class="specHeader Header" colspan="2"><a class="c27 fs22">Handheld Transmitter</a></th></tr><tr><td class="specTopic c28 fs14 bold"> Frequency </td><td class="specDetail c28 fs14"> Not specified by manufacturer </td></tr><tr><td class="specTopic c28 fs14 bold"> Display </td><td class="specDetail c28 fs14"> Color Screen for menu and live flight telemetry </td></tr><tr><td class="specTopic c28 fs14 bold"> Battery </td><td class="specDetail c28 fs14">Chemistry: Lithium-polymer<br>Capacity: 5200 mAh<br>Voltage: 14.8 VDC<br>Life: Up to 4 hours</td></tr></tbody></table>
<table class="specTable" border="1"><tbody><tr><th class="specHeader Header" colspan="2"><a class="c27 fs22">Mobile App</a></th></tr><tr><td class="specTopic c28 fs14 bold"> System Requirements </td><td class="specDetail c28 fs14"> Wi-Fi enabled iOS or Android mobile device </td></tr><tr><td class="specTopic c28 fs14 bold"> Wi-Fi Range </td><td class="specDetail c28 fs14"> Up to 2640' / 805 m (depending on environment) </td></tr></tbody></table>
<table class="specTable" border="1"><tbody><tr><th class="specHeader Header" colspan="2"><a class="c27 fs22">FPV and Monitoring</a></th></tr><tr><td class="specTopic c28 fs14 bold"> Video Downlink </td><td class="specDetail c28 fs14"> Latency: 180 ms </td></tr><tr><td class="specTopic c28 fs14 bold"> Connectivity </td><td class="specDetail c28 fs14"> 1 x HDMI output on Transmitter </td></tr></tbody></table>
<table class="specTable" border="1"><tbody><tr><th class="specHeader Header" colspan="2"><a class="c27 fs22">Components</a></th></tr><tr><td class="specTopic c28 fs14 bold"> Rotors </td><td class="specDetail c28 fs14"> 4 x 10 x 4.5" / 25.4 x 11.4 cm self-tightening props </td></tr><tr><td class="specTopic c28 fs14 bold"> Motors </td><td class="specDetail c28 fs14"> Velocity Constant: 880 kV </td></tr><tr><td class="specTopic c28 fs14 bold"> Gimbal Compatibility </td><td class="specDetail c28 fs14"> Solo Gimbal for HERO3+ and HERO4 (gimbal and camera available separately) </td></tr></tbody></table>
<table class="specTable" border="1"><tbody><tr><th class="specHeader Header" colspan="2"><a class="c27 fs22">Flight Battery</a></th></tr><tr><td class="specTopic c28 fs14 bold"> Model </td><td class="specDetail c28 fs14"> Solo Battery </td></tr><tr><td class="specTopic c28 fs14 bold"> Chemistry </td><td class="specDetail c28 fs14"> Lithium-polymer </td></tr><tr><td class="specTopic c28 fs14 bold"> Capacity </td><td class="specDetail c28 fs14"> 5200 mAh </td></tr><tr><td class="specTopic c28 fs14 bold"> Voltage </td><td class="specDetail c28 fs14"> 14.8 VDC </td></tr></tbody></table>
<table class="specTable" border="1"><tbody><tr><th class="specHeader Header" colspan="2"><a class="c27 fs22">General</a></th></tr><tr><td class="specTopic c28 fs14 bold"> Running Lights </td><td class="specDetail c28 fs14"> Customizable color LEDs to assist orientation </td></tr><tr><td class="specTopic c28 fs14 bold"> Dimensions </td><td class="specDetail c28 fs14"> Not specified by manufacturer </td></tr><tr><td class="specTopic c28 fs14 bold"> Weight </td><td class="specDetail c28 fs14">Unladen: 3.3 lb / 1.5 kg<br>With Solo Gimbal and GoPro: 4 lb / 1.8 kg</td></tr></tbody></table>
<table class="specTable" border="1"><tbody><tr><th class="specHeader Header" colspan="2"><a class="c27 fs22">Packaging Info</a></th></tr><tr><td class="specTopic c28 fs14 bold"> Package Weight </td><td class="specDetail c28 fs14"> 12.0 lb </td></tr><tr><td class="specTopic c28 fs14 bold"> Box Dimensions (LxWxH) </td><td class="specDetail c28 fs14"> 16.7 x 16.3 x 9.1" </td></tr></tbody></table>


This is written in product description but displaying just like simple paragraph text

**Comment by Andrew-Orlov** [comment]
For product description on Electronics theme was applied Liquid-filter `strip_html`. Removed.

**Comment by Dhiren-K** [comment]
So what i have to change to make it working?

**Comment by Andrew-Orlov** [comment]
@Dhiren-K You can take the last version of Dev branch or remove this filter manually by yourself. You can locate it in App_Data / Themes / default / templates / product.liquid file at 145 line: `{{ product.description | strip_html }}`. Just remove `| strip_html`.

**Comment by Dhiren-K** [comment]
Thanks. It worked.
