### ISSUE TITLE
Admin throws 500 to Storefront because of the Response Time filter

### ISSUE THREAD

**Issue by attilah** [VirtoCommerce/vc-community#470]
I've an Azure deployment of the empty Storefront and Manager, it worked, but after instlaling and uninstalling modules, it started to throw 500 errors.

Here is the stacktrace I get on frontend, but it does not help much.

VirtoCommerce.Client.Client.ApiClient.Deserialize(IRestResponse response, Type type) in C:\Workspaces\Private\attilah\vc-community\SDK\DotNet\VirtoCommerce.Client\Client\ApiClient.cs:288
   VirtoCommerce.Client.Api.<StoreModuleGetStoresAsyncWithHttpInfo>d__29.MoveNext() in C:\Workspaces\Private\attilah\vc-community\SDK\DotNet\VirtoCommerce.Client\Api\StoreModuleApi.cs:1167
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13847892
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +31
   VirtoCommerce.Client.Api.<StoreModuleGetStoresAsync>d__28.MoveNext() in C:\Workspaces\Private\attilah\vc-community\SDK\DotNet\VirtoCommerce.Client\Api\StoreModuleApi.cs:1113
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13847892

I debugged the Manager and I found out that it fails on this line with nullreferenceexception in ResponseTimeHeaderFilter:

```
var stopWatch = timer as Stopwatch;
--> stopWatch.Stop();
```

Somehow stopWatch is not getting added to the request at the beginning?!

When I upload a module from the Admin I can catch the real stacktrace:

```

  "message": "An error has occurred.",
  "exceptionMessage": "Object reference not set to an instance of an object.",
  "exceptionType": "System.NullReferenceException",
  "stackTrace": "   at VirtoCommerce.Platform.Web.ResponseTimeHeaderFilter.OnActionExecuted(HttpActionExecutedContext actionExecutedContext) in C:\\Workspaces\\Private\\attilah\\vc-community\\PLATFORM\\VirtoCommerce.Platform.Web\\App_Start\\FilterConfig.cs:line 33
at System.Web.Http.Filters.ActionFilterAttribute.OnActionExecutedAsync(HttpActionExecutedContext actionExecutedContext, CancellationToken cancellationToken
```

UPDATE: I was able to narrow this bug down to the case, when the execution is going to an error path. For example if you upload a corrupt module archive (invalid zip) this error can be reproduced.

I think the easy fix is a null check on the timer object because of the cast operator it can be null.

**Comment by tatarincev** [comment]
I've added null check as you suggest.
