### ISSUE TITLE
hu flag (maybe others as well) are missing in link list view

### ISSUE THREAD

**Issue by attilah** [VirtoCommerce/vc-community#473]
flag- style added instead of flag-hu style for the flag in link list view.

![image](https://cloud.githubusercontent.com/assets/230432/15637479/cfbb6d46-25e5-11e6-9b44-eec1f9ec4676.png)

**Comment by tatarincev** [comment]
Need to rid all flags icon for languages in manager. Leave only culture name.
But only after 2.11 release to prevent manual merging to modules repositories.

**Comment by attilah** [comment]
I've not problem with flag images, but do as you wish ;-)

**Comment by eMazeika** [comment]
done in https://github.com/VirtoCommerce/vc-module-content/tree/dev
