### ISSUE TITLE
Asset image url not resolved correctly from blob storage

### ISSUE THREAD

**Issue by attilah** [VirtoCommerce/vc-community#477]
I've an image within my theme's assets/images folder hero1920.jpg.

It it at the same location in the FileSystem, like in the Blob Storage, same path, everything (import/export) but the url is not resolved to on the site which is using the blob storage.

```
http://www.myshop.com/hu-HU/themes/assets/images/hero-1920.jpg
```

It is not language dependent, I tried that already.

This is a blocking bug for me.

I debugged this and as I suspected it goes down to how AzureContentBlobProvider.Search method handles path and searchPattern parameters.

It does not check for slashes in the searchPattern (filename) part that is the reason why it fails.

Maybe it works with the FilesystemContentBlobProvider class, because CLR's Directory class is smart enough?! since there is no path part handling in that code either.

**Comment by tatarincev** [comment]
Thanks for awesome bug report. Here hot fix - https://github.com/VirtoCommerce/vc-community/commit/3d223b7f66622d896ec45aab683fa266d196db3b
