### ISSUE TITLE
B2B - Quotes

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-community#48]
Quoter enables business users to execute quote requests online. Once initiated, an online conversation takes place with internal users who interact with the business user’s request. The internal user can set prices for quantity breaks or discounts. The quote is then made available to the business user online. The business user can accept the quote and place the order, continue the conversation, or reject the quote.

**Realization plan**:
Implement new module VirtoCommerce.Quotes with API and UI allow to manage cutomer quotes on backend.
Extend frontend  to allow customer make a quote requests and see history and details.

**Comment by eMazeika** [comment]
Proposed quotation management wireframe: http://e0ajh3.axshare.com/#p=homepage
