### ISSUE TITLE
Price lists for companies

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-community#49]
Allow to make personal price lists assigned  for concrete companies or customers.

**Realization plans**
Extend price list by new properties.

**Comment by jvdonk** [comment]
Hi, issue is still open but was tagged with v2.5.

With 2.6 pre-released, what is the status for this functionality? We want to use customized pricing on a per customer basis.

Thank you, very nice project!

**Comment by tatarincev** [comment]
Hi @jvdonk. We added dynamic expressions evaluation for price list assignments (in prev version it was disable) and add new Tags contains expression.
![image](https://cloud.githubusercontent.com/assets/7566324/12051295/316f3bec-af0a-11e5-8a8e-cd7c33b3302a.png)

You can used it to check customer organization, but previously you should write customer organization in evalContext.Tags property 
http://demo.virtocommerce.com/admin/docs/ui/index#!/Pricing_module/PricingModule_EvaluatePrices

Or you can define you own dynamic expression (example Customer organization expression) and add to price list assignment expression tree.
http://docs.virtocommerce.com/display/vc2devguide/Composing+dynamic+conditions

**Comment by jvdonk** [comment]
Where would one define tags for customers? Not to be confused with liquid tags?

Thank you for your quick response, implementing DynamicExpression/IConditionExpression provides great flexibility.

**Comment by tatarincev** [comment]
In storefront here VirtoCommerce.Storefront.CatalogSearchServiceImpl.LoadProductsPrices method.

**Comment by jvdonk** [comment]
I'm looking for a end-user friendly solution to provide differentiated pricing(also higher prices) based on the shopping Customer. No problem to develop custom modules or DynamicExpression etc.

But in the end, the "Pricing manager"-user must be able to use the Manager UI to specify on a per customer(or organisation) basis, what displayed price is in the storefront is. That he can choose that Customer 1 gets a 10% discount(on every product, or maybe product-group(s)?) and Customer 2 gets a 20% increase, etc.

DynamicExpression looks promissing but I can't find a way to specify the customers side of the implementation: specify what discount or increase of pricing should be applied.

Also, I have no idea what you meant with your last comment about the LoadProductsPrices in comparison with the Tags? Certainly it must be my lacking experience with VirtoCommerce.

Thank you.

**Comment by tatarincev** [comment]
I understand what you mean.

For your described case you can define multiple price lists to same products and next you can configure pricing  assignments by using special conditions (dynamic expression) so works price segregation. 

 I create for you some example pricelist on our demo manager. Two price lists *RetailPhonesUSD* and *WholesalePhonesUSD* acting for different customer groups. http://demo2.virtocommerce.com/admin#/workspace/pricing
![1](https://cloud.githubusercontent.com/assets/7566324/12053303/518cd66c-af20-11e5-81d6-ec57e0947cef.PNG)
![2](https://cloud.githubusercontent.com/assets/7566324/12053364/1a770b06-af21-11e5-90f2-73b757e20871.PNG)
Instead tags there can be other expression (**For organization**  or **For customer with status** for example)

In additional for  more convenient pricing management we have plans to use Excel  as main tools for pricing  management (because excel has more powerful abilities for this - formulas, templates etc).

But for dynamic discounts related from user context  as you mentioned I think you should better use promotions from Marketing module.
http://docs.virtocommerce.com/display/vc2userguide/Promotions

If you want you can send to us your pricing requirements and we send to you more expanded explanation how better use our system for your tasks.

**Comment by jvdonk** [comment]
Yes, "customer with status" sounds about right. Where, from the Customer perspective, would I define this status?

Dynamic properties? I defined a dynamic property(Collection type) on the Customer entity with a list of possible statussus. Are those DynamicFields accessible from the executing DynamicExpression? I didn't tried that yet.

Separate question, maybe I should open a different 'issue' but here we go: what extentionbility points are there for (Platform) Entitties. In Orchard(that's where I got sight of VitroCommerce, in the Podcast where you demo'ed your Orchard solution, you can extend ContentTypes with custom parts. As you developed Orchard modules I think you met these concepts: ContentTypes, ContentParts, etc.

Any insights on VirtoCommerce from this perspective? For example extending the Customer/Organisation-entity with a custom 'status' field.

**Comment by tatarincev** [comment]
First, the answer to your first question.
There is no way to check dynamic properties in the expressions now, but its the a good idea to implement it.
I think in the next release we will be able to add this feature.
And then you will be able to determine dynamic properties (for the shopper as an example) and use them in expressions.

Next, I'll try to answer you the second difficult question.
There are two basic approaches to extend the object.
**Design time extension** and **Runtime extension**.

**Design time object extension** - is used when besides of adding the new property to the object you want to change the behavior of the application logic
(*for example by adding a 'status' field, you would probably need take it into an account in your application logic, use for data filtering etc.*). All that means it would likely require to modify the database and code.

**Runtime object extension** - is when you have developed the application logic given that the object facilities can be arbitrary set of properties that can
be modified during the application operation (*e.g. new user registration form where any count of fields can be filled and saved with the object*).
In this case you don't need to modify application logic to expand the object, you just add new object properties through the user interface.

Thus, when you want extend the object you have to decide which approach of object extension to choose.
In some cases one option may be more preferable to another and vise versa.
In our system DynamicProperties suits to runtime object extension approach.
The Design Time object extension can be achieved with Visual Studio + C # compiler.

**Comment by jvdonk** [comment]
So when you mentioned **For customer with status** in:
```
Instead tags there can be other expression (For organization or For customer with status for example)
```

you didn't specifically had a solution in mind, e.g. Dynamic properties(because: currently not supported). 

Or did you meant to implement either the design time object extension or the runtime object extension? 

Or maybe there is some other way to accomplish this *Customer with status* that isn't yet mentioned?

**Comment by tatarincev** [comment]
I mean we will  implement check dynamic properties condition  in next release. Currently its not supported from scratch.
