### ISSUE TITLE
Generate module API client

### ISSUE THREAD

**Issue by jvdonk** [VirtoCommerce/vc-community#514]
I developed a custom module with some new api's and want to generate a client for it, using the development guide: http://docs.virtocommerce.com/display/vc2devguide/How+to+generate+module+API+C%23+client

I'm using the <VC-URL>/docs/v1 generated json for the api-json file parameter in the generate-vc-client.bat file and a self made codegen-config.json because I don't know what to use otherwise:

```
{
    "packageName": "MODULENAME.Client"
}
```

This generates a client with both the platform API's as well as all the custom module API's. This is of course caused by the api-json from the /docs/v1 url which contains all the API references.

I can manually edit this json to remove all the unnecessary API references but there has to be a better way right? How do I get the api-json for just 1 custom module then?

The second problem I have(which maybe related) is that all the types generated by the swagger-codegen are prefixed with the namespace they were in. So the an "Address" type becomes in the generated c# code: MyNamespaceWithModuleNameAddress-type.

How do I end up with just the original types in the generated model classes.

BTW the generated code works perfectly in a sample client using the generated api-client.

**Comment by artem-dudarev** [comment]
/docs/v1 URL generates JSON which contains API resources from platform and all modules.
You should use /docs/<your-module-id>/v1 which will contain only your API resources and they will have short names without namespaces.

**Comment by jvdonk** [comment]
Somewhere I need to inject the module name in the URL for sure. But your /docs//v1 suggestion doesn't tell me where and how :)

Maybe you forgot something in your suggestion on which URL to use?

**Comment by jvdonk** [comment]
Found it: /docs/MODULE-ID/v1

**Comment by jvdonk** [comment]
And generated code is without namespace/modules names-prefixes.

Excellent, thank you!
