### ISSUE TITLE
UI Grid reactive integration instead static tables

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-community#55]
https://github.com/angular-ui/ui-grid

**Comment by Woland2k** [comment]
What is the line at the bottom of the grid? Can we remove that?

![image](https://cloud.githubusercontent.com/assets/1566470/11315084/6e3831ba-8fa1-11e5-8168-d091d1b57cae.png)

**Comment by eMazeika** [comment]
that's horizontal scrollbar (in disabled state). We're planning to change it's color, but can't remove it as scrolling functionality is needed.

**Comment by Woland2k** [comment]
Can we remove it when scrolling is not required?

**Comment by eMazeika** [comment]
we've overridden the behavior to display scroll as needed

**Comment by Woland2k** [comment]
great, thanks
