### ISSUE TITLE
Unknown provider: taOptionsProvider <- taOptions

### ISSUE THREAD

**Issue by Wirwing** [VirtoCommerce/vc-community#56]
Hi.

I'm trying to run VC Manager 2.4 locally. Pulled lastest code from master branch, created a new db user and configured all folder permissions. On running the project with VS the database get created, but home gives me a blank page. Chrome console complains about:

Uncaught Error: [$injector:unpr] Unknown provider: taOptionsProvider <- taOptions

Am I missing something?

**Comment by tatarincev** [comment]
A quick workaround this issue is to: use Debug build configuration and make sure that ..\platform\virtocommerce.platform.web\web.config system.web\compilation section has debug="true":
We had this minification related bug and it was fixed on September 10: https://github.com/VirtoCommerce/vc-community/commit/b131995f450eee7eae9f7bed8b916073e2f853a1

**Comment by eMazeika** [comment]
Make sure the Modules virtual folder is configured correctly as described in http://docs.virtocommerce.com/display/vc2devguide/Source+Code+Getting+Started

**Comment by kodermax** [comment]
i have this problem too

**Comment by Woland2k** [comment]
Did the workaround above solve the problem for you?

**Comment by kodermax** [comment]
workaround don't help

**Comment by kodermax** [comment]
http://clip2net.com/s/3nZUvMF

**Comment by ptsteadman** [comment]
I cloned the project a few hours ago and am trying to run it.  When I run the platform directly in Visual Studio, I get this error in both Debug and Release modes.  I also followed the directions in the "Getting Started" section, and get a different error when I attempt to browse to localhost/admin:

```
Unable to find the specified file.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.IO.FileNotFoundException: Unable to find the specified file.

Source Error: 

Unable to find the specified file.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.IO.FileNotFoundException: Unable to find the specified file.

Source Error: 

Line 41:             if (!File.Exists(assemblyUri.LocalPath))
Line 42:             {
Line 43:                 throw new FileNotFoundException();
Line 44:             }
Line 45: 

Source File: c:\Users\Patrick\Documents\GitHub\vc-community\PLATFORM\VirtoCommerce.Platform.Core\Modularity\AssemblyResolver.cs    Line: 43 
```

I assume these issues are unrelated?

**Comment by kodermax** [comment]
debug and release hsa this error.

**Comment by tatarincev** [comment]
I commit possible fix for problem 'taOptionsProvider'  in master 5 min ago.  To prevent repeat downloading and compilation  i suggest to add one line of code to vc-community-master\PLATFORM\VirtoCommerce.Platform.Web\Scripts\app\app.js. Add to line 23 
```javascript
 'ui.codemirror',
  'focusOn',
  'textAngular', //ADD this line
  'ngTagsInput'
];
```

**Comment by tatarincev** [comment]
ptsteadman. Can you try to move project from windows  User directory to another place? Because in User directory may be problem with security.

**Comment by kodermax** [comment]
thank you, this problem is solved, but i see new error http://clip2net.com/s/3o1wAwx
