### ISSUE TITLE
platform manager doesn't work with empty catalog

### ISSUE THREAD

**Issue by kodermax** [VirtoCommerce/vc-community#57]
I install vc 2.4 and choose empty installation, and now manager panel dosn't work. item "browse" doesn't work

**Comment by tatarincev** [comment]
can you check that have correct mapped Modules virtual folder in iis application?

**Comment by kodermax** [comment]
my Modules folder
http://c2n.me/3o1IpDs

**Comment by tatarincev** [comment]
Can this problem relate to you another post about server error or this error no more?

**Comment by kodermax** [comment]
now i clone vc and try install, problem too

**Comment by artem-dudarev** [comment]
The Modules virtual directory must be inside the admin virtual application.
http://docs.virtocommerce.com/display/vc2devguide/Source+Code+Getting+Started

**Comment by kodermax** [comment]
Thank you. The problem is solved.
