### ISSUE TITLE
connectionStrings is absent

### ISSUE THREAD

**Issue by kodermax** [VirtoCommerce/vc-community#58]
i can't find this file In the VirtoCommerce.Website project edit the file App_Data\configuration\connectionStrings.config.

in 2.4 verion.

P.S. Вообщем уже года 2 слежу за этим проектом, а может и больше, еще ни разу не удавалась установить без косяков коробочный вариант.

**Comment by tatarincev** [comment]
Connection strings started from 2.1 version  defined in web.config.

**Comment by kodermax** [comment]
so you must change documentation about this http://docs.virtocommerce.com/display/vc2devguide/Source+Code+Getting+Started

**Comment by tatarincev** [comment]
Sure, we change docs, thank for you help.

**Comment by kodermax** [comment]
thanks.
