### ISSUE TITLE
Fulfilment Admin view not easy to understand

### ISSUE THREAD

**Issue by MarkOGDev** [VirtoCommerce/vc-community#6]
In the View:  Management Application  -->  Fulfillment --> Inventory:

The “Sku” Column in the grid view is not displaying the correct data.

It is displaying the ‘ItemId’ of the item record. The ‘ItemId’ is not useful to the user because it is an auto-generated value.

I think the user needs to see the ‘Code’ and ‘Name’ of the item record in the Grid View.

I also notice that in the Database the Inventory Table has a column called 'SKU' but we are saving the 'ItemId' into this column and not the 'code' of the item. Should this column contain the 'code' of the item?

**Comment by Woland2k** [comment]
We are changing this in VC 2.0.
