### ISSUE TITLE
Show Id catalog entity

### ISSUE THREAD

**Issue by kodermax** [VirtoCommerce/vc-community#62]
I'd like to see in the admin panel id catalog, id category, id product.

**Comment by tatarincev** [comment]
In most cases Id is GUID that informations may make ugly any UI, but we promise to think how it make more comfortable for eyes.

**Comment by kodermax** [comment]
thank you. it's need for rest api.

**Comment by tatarincev** [comment]
We added VirtoCommerce.Platform.Data.Infrastructure.Interceptors.GuidCombiPrimaryKeyGeneratorInterceptor for more human friendly primary keys generation and also add customizeble ui grid in Manager.
