### ISSUE TITLE
button refresh in catalog

### ISSUE THREAD

**Issue by kodermax** [VirtoCommerce/vc-community#63]
I'd like to see button Refresh for module Catalog.

**Comment by tatarincev** [comment]
![capture](https://cloud.githubusercontent.com/assets/7566324/10133046/bb9ebcc6-65da-11e5-9537-6efbdc43364b.PNG)

For you, it is not available?

**Comment by kodermax** [comment]
i'd like to see this button on this http://demo.virtocommerce.com/admin#/workspace/catalog

**Comment by tatarincev** [comment]
This buton was added only in dev branch and has not yet updated on demo site. We have plans to  make release on end of this week.

**Comment by kodermax** [comment]
It's great news.
