### ISSUE TITLE
Removing assets using REST interface?

### ISSUE THREAD

**Issue by Esbob** [VirtoCommerce/vc-community#64]
Using the RESTful "POST /api/platform/assets/{folder}" assets can be uploaded to blob storage, but how to delete these assets again? The REST API documentation does not list a DELETE operation for assets. Is there an undocumented way to do it? 
By the way, your new REST API documentation is awesome :-) 
Now I just hope the interface will remain relatively stable...

**Comment by tatarincev** [comment]
In the current version its not possible do it by using api, we certainly add this method in next release.

Also we have plans extend  platform assets functionality add UI allow  to working with  files and folders more comfortable.

Thanks for you  review, our API documentation generated automaticaly by VirtoCommerce.Swashbuckle module,  this allows us to always keep it up to date.
