### ISSUE TITLE
Work on Linux

### ISSUE THREAD

**Issue by kodermax** [VirtoCommerce/vc-community#69]
Does your project work on the Linux?

**Comment by tatarincev** [comment]
Platform designed and worked only MS product stack technology (.NET framework, ASP.NET MVC, WEB API, EF etc). Client of our API may be in any platform and there no limitation.

**Comment by kodermax** [comment]
Have you tested it to work on Linux?

**Comment by tatarincev** [comment]
No, You mean test by windows emulator?

**Comment by kodermax** [comment]
I mean mono.

**Comment by tatarincev** [comment]
no
