### ISSUE TITLE
Preintegrate modules in custom build

### ISSUE THREAD

**Issue by Wirwing** [VirtoCommerce/vc-community#80]
Is it possible to integrate modules (like commerce store, commerce catalog) in a build, so they get configured in the first run. I need to make some modifications in a couple of them, and removing/adding in each change seems cumbersome.

Right now the only way I found for adding a module is through the Configuration -> Modules -> Add option inside the Admin backend.

Thanks in advance. :)

**Comment by Woland2k** [comment]
Once in VS.NET and you modified something in the module, just build the solution and then rebuild Platform.Web project. That will cause website to restart and re-add the new modified modules.
