### ISSUE TITLE
DynamicContent on sample clothing store homepage

### ISSUE THREAD

**Issue by markwedinger** [VirtoCommerce/vc-community#86]
There are 2 data-vccontentid's in the index.liquid template (benefitsbanner, homepageslider).  Neither of them are rendering for some reason.

There are coming back from the service and actually DO hit the virtocommerce.js VirtoCommerce.renderDynamicContent  function but its not rendering. 

Could you walk this and see if you see the same behavior?

im on v2.4.644.

**Comment by Woland2k** [comment]
It works in our demo store: http://demo.virtocommerce.com/electronics. The dynamic content is displayed. Do you see any errors in chrome developer console?

**Comment by markwedinger** [comment]
No errors in console.  The template index template in the version i have is definitely different..

I see the following it in;

<div data-vccontentid="BenefitsBanner"></div>
<div data-vccontentid="HomePageSlider"></div>

**Comment by Woland2k** [comment]
I would update to the latest 2.5 version as we fixed many issues in frontend and backend. The JS api should pick up the divs with contentid specified and populate it with dynamic data.
