### ISSUE TITLE
Invalid column name 'id'. 

### ISSUE THREAD

**Issue by Rushmore74** [VirtoCommerce/vc-community#99]
Complete clean installation using the getting started documentation (latest sources).

Running http://localhost/admin will create the database and tables, after that (or during) it throws an exception:

[SqlException (0x80131904): Invalid column name 'id'.]
   System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) +3242916
   System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) +345
   System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) +4927
   System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite) +1287
   System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite) +367
   System.Data.SqlClient.SqlCommand.ExecuteNonQuery() +386
   System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch(TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed) +104
   System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext) +505
   System.Data.Entity.Migrations.DbMigrator.ExecuteSql(DbTransaction transaction, MigrationStatement migrationStatement, DbInterceptionContext interceptionContext) +189
   System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbTransaction transaction, DbInterceptionContext interceptionContext) +114
   System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection) +854
   System.Data.Entity.SqlServer.<>c__DisplayClass1.<Execute>b__0() +15
   System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute(Func`1 operation) +238
   System.Data.Entity.Migrations.DbMigrator.ExecuteStatements(IEnumerable`1 migrationStatements, DbTransaction existingTransaction) +271
   System.Data.Entity.Migrations.DbMigrator.ExecuteOperations(String migrationId, XDocument targetModel, IEnumerable`1 operations, IEnumerable`1 systemOperations, Boolean downgrading, Boolean auto) +1231
   System.Data.Entity.Migrations.DbMigrator.ApplyMigration(DbMigration migration, DbMigration lastMigration) +526
   System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId) +193
   System.Data.Entity.Migrations.DbMigrator.UpdateInternal(String targetMigration) +609
   System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase) +613
   System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration) +116
   VirtoCommerce.Platform.Data.Infrastructure.SetupDatabaseInitializer`2.InitializeDatabase(TContext context) +412

[ApplicationException: Migrations failed with error "Invalid column name 'id'."]
   VirtoCommerce.Platform.Data.Infrastructure.SetupDatabaseInitializer`2.InitializeDatabase(TContext context) +584
   VirtoCommerce.CatalogModule.Web.Module.SetupDatabase() +178
   VirtoCommerce.Platform.Core.Modularity.ModuleInitializer.Initialize(ModuleInfo moduleInfo) +92

[ModuleInitializeException: An exception occurred while initializing module 'VirtoCommerce.Catalog'.]
   VirtoCommerce.Platform.Core.Modularity.ModuleInitializer.HandleModuleInitializationError(ModuleInfo moduleInfo, Exception exception) +378
   VirtoCommerce.Platform.Core.Modularity.ModuleInitializer.Initialize(ModuleInfo moduleInfo) +220
   VirtoCommerce.Platform.Core.Modularity.ModuleManager.LoadModulesThatAreReadyForLoad() +312
   VirtoCommerce.Platform.Web.Startup.Configuration(IAppBuilder app, String virtualRoot, String routPrefix) +2046

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +128
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +146
   Owin.Loader.<>c__DisplayClass12.<MakeDelegate>b__b(IAppBuilder builder) +93
   Owin.Loader.<>c__DisplayClass1.<LoadImplementation>b__0(IAppBuilder builder) +209
   Microsoft.Owin.Host.SystemWeb.OwinAppContext.Initialize(Action`1 startup) +843
   Microsoft.Owin.Host.SystemWeb.OwinBuilder.Build(Action`1 startup) +51
   Microsoft.Owin.Host.SystemWeb.OwinHttpModule.InitializeBlueprint() +101
   System.Threading.LazyInitializer.EnsureInitializedCore(T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory) +141
   Microsoft.Owin.Host.SystemWeb.OwinHttpModule.Init(HttpApplication context) +172
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +618
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +419
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +343

[HttpException (0x80004005): Exception has been thrown by the target of an invocation.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +579
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +120
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +712

Any help are appreciated.

Regards
Carlo

**Comment by tatarincev** [comment]
Can you drop database then reset IIS and try open manger again?

**Comment by Rushmore74** [comment]
Id did it already. Same behavior. Sasha told me the same thing this morning.
Any other suggestions?

**Comment by tatarincev** [comment]
Can you send me you IIS application screenshot  like this
![image](https://cloud.githubusercontent.com/assets/7566324/10511937/1814717a-733d-11e5-9ea7-89a2d48a87e5.png)

**Comment by Rushmore74** [comment]
I run the deploy.cmd, after that I´ve a artifacts/wwwroot folder. Then I copied the contents to my IIS. I´ve set the permission on the folder how described in the documentation. But I´ve only this:

[cid:image001.png@01D1074B.1B587A60]

**Comment by tatarincev** [comment]
can you re-upload screenshot i cannot see it in your answer

**Comment by Rushmore74** [comment]
Image below:

[cid:image001.png@01D10754.AFE51BD0]

**Comment by tatarincev** [comment]
Can you describe all steps that you did during the installation?  (you scrren shot unavailable for me)

**Comment by tatarincev** [comment]
I just test by follow steps:
1. Download and unpack 2.5 release to c:\tmp\vc-community-2.5
2. run Deploy.cmd after finish should appear folder  c:\tmp\vc-community-2.5\artifacts
3. Create application in IIS http://localhost/platform and point it to c:\tmp\vc-community-2.5/artifact/admin
4. Open http://localhost/platform in browser and see login page (all ok)

**Comment by Rushmore74** [comment]
Sorry, but I get the same error Invalid column name 'id'.

Maybe we can do a Skype conference tomorrow @ 13:30 UTC+1

Kind regards
Carlo

**Comment by artem-dudarev** [comment]
This is because the default collation on your SQL server is case sensitive and one of the migrations in the Catalog module references the id column in the Item table while the actual column name is Id.
I have fixed the migration - please download the latest code and try again.

**Comment by Rushmore74** [comment]
That´s it. Thank you.

Regards
Carlo
